---
sidebar: sidebar
permalink: aqos-kfs.html
keywords: aqos, qos, adaptive quality of service, quality of service
summary: Keystone adaptive quality of service (AQoS)
---

= Adaptive Quality of Service in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Storage quality of service (QoS) is a critical technology that ensures that applications obtain consistent and predictable performance. Without QoS, certain workloads, such as those for booting of multiple systems, may consume most or all of of the resources for a period, and affect other workloads. For information about QoS, see https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html[Guarantee throughput with QoS overview^].

== Adaptive QoS
Adaptive QoS (AQoS) is used by Keystone services to dynamically maintain the IOPS/TiB ratio based on the volume size. For information about AQoS policies, see https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html#about-adaptive-qos[About adaptive QoS^].

Keystone provides you with AQoS polices that you can set up once your cluster is in production. You should ensure that all your volumes are associated with the correct AQoS policies that are already created and available in your system.

An ONTAP volume is non-compliant if it does not have an AQoS policy applied. A volume without a QoS policy is the last on the list of priority for the system to provide any available input-output operations. However, if any input-output operations are available, then the volume could consume all available IOs.

[NOTE]
If you have not applied AQoS policies to your volumes, those volumes will be measured and charged at the highest service level as per your subscription. This may result in unintended burst charges.

=== Adaptive QoS settings
The Adaptive QoS (AQoS) settings vary with service levels.

|===
|*Policy name* | *Extreme* and *Extreme Tiering* |*Premium* and *Premium Tiering* |*Standard* |*Value*
|*Expected IOPS* |6,144 |2,048 |128 |64
|*Expected IOPS Allocation*
4+| Allocated space
|*Peak IOPS* |12,288 |4,096 |512 |128
|*Peak IOPS Allocation*
4+| Allocated space
|*Block Size*
4+| 32K


|===
