---
sidebar: sidebar
permalink: nkfsfaq_keystone_subscription.html
keywords: netapp, keystone, subscription, subscriptions,
summary: NetApp Keystone Subscription
---

= NetApp Keystone Flex Subscription
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:15:36.922050
//

[.lead]
*What is the minimum committed capacity?*

The minimum committed capacity for a NetApp Keystone Flex Subscription (Flex Subscription) is 100 TiB, per site across one or more service tiers.

*What does Flex Subscription map to?*

Flex Subscription maps to a single site or a single data center and it can comprise of different performance service levels.

*How can I increase the committed capacity in a subscription?*

You can submit a capacity addition request through the NetApp Service Engine management tool or through their NetApp Keystone success manager.

*Does increasing the capacity extend the term?*

All the additions are co-term to the existing term period, except if the request is made in the last 90 days of the subscription, in which case the term must extend for at least 12 months.

*Does a new subscription have flexibility to come with a new yearly term?*

Yes, new subscriptions can have new terms separate from any existing subscriptions.

*Can I mix multiple subscriptions on the same ONTAP cluster?*

No, each cluster is assigned to a particular subscription.

*Can I reduce the committed capacity?*

No. During a term, the committed capacity can only be increased but not decreased.

*What is burst capacity?*

You can increase and decrease usage up to 20% above the committed capacity. The burst capacity usage is measured on a daily basis and billed only when used.

For example, if the committed capacity is 100 TiB, you can burst up to 120 TiB.

*Is there a premium charge for using burst?*

The burst capacity usage up to 20% of committed capacity is billed at the same rate as committed capacity, any usage above 20% of committed capacity is billed at 50% premium.

*What is the benefit of burst capacity?*

Burst capacity gives you the flexibility to consume storage on demand versus committing for the long term.

*Where can I see the committed and burst capacity usage?*

NetApp Service Engine has built-in dashboards to report consumed capacity against committed capacity.

*Will there be any notifications if I reach a certain percentage in committed capacity usage?*

Yes, the management tools provide notifications on capacity usage through the NetApp Service Engine dashboard.
