---
sidebar: sidebar
permalink: nkfsosm_netapp_global_services_and_support_center_@gssc@.html
keywords: netapp, keystone, global, services, support, center, gssc,
summary: NetApp Global Services and Support Center (GSSC)
---
=

:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:48.538983
//

[.lead]
NetApp Keystone Flex Subscription Services are run by leveraging the NetApp Global Services and Support Center (GSSC), Keystone Success Manager, and Keystone Service Delivery Manager.

== NetApp Global Services and Support Center (GSSC)
NetApp provides operational services remotely to NetApp Keystone customers. These services encompass a range of operational disciplines across storage management activities, including asset and configuration management, capacity and performance management, change management, event, incident and problem management, service request fulfillment, and reporting. NetApp will demonstrate a state of control and supporting evidence available as required.

== Additional Information and Support Contact

The NetApp Global Services and Support Center (GSSC) team primarily support the services to Keystone customers.

Raise a ticket directly from the NetApp Service Engine portal (*Support > Service Requests*) with the appropriate details of the issue for assistance.

You can also use the following information to reach out to the support team.

* Global Service Contacts :
https://www.netapp.com/us/contact-us/support.aspx

* If you have an open case/ticket that needs to be escalated, please send an email to one of the following addresses:
Keystone.services@netapp.com
Keystone.escalations@netapp.com

* NetApp uses OpsRamp, a cloud-based remote gateway solution to proactively monitor and connect to the Keystone environment for troubleshooting purposes. For information on OpsRamp, see https://www.opsramp.com/#.


To learn more about the information that is described in this document, review the following documents and/or websites:

* NetApp Keystone
 https://www.netapp.com/us/solutions/keystone/index.aspx[https://www.netapp.com/us/solutions/keystone/index.aspx^]
* NetApp Product Documentation
 https://docs.netapp.com[https://docs.netapp.com^]
