---
sidebar: sidebar
permalink: nkfsosm_performance.html
keywords: netapp, keystone, performance, service levels
summary: Keystone performance
---

= Performance service levels in Keystone
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:47.987174
//

[.lead]
NetApp Keystone offers capacity and capacity at predefined performance service levels (service levels). Subject to the terms of the service description and the applicable Keystone order, service levels are defined as the ratio of the maximum IOPS (read-write input-output operations per second) per tebibyte (TiB) of the allocated space for a volume at average latency.  

Each volume managed by the Keystone services is associated with a service level. All I/O operations and all used storage used on the respective volume are factored into the volume's I/O density calculation, that is IOPS per TiB per volume.

== Service levels for difference storage types

The service levels for file, block, and object storage are listed here.

I/O density calculations at the volume level are reported to show peak I/O density during the prior week. The peak performance is determined on an hourly time interval. I/O density reports by volume are generated monthly to gauge adherence to the respective service levels.

=== File service

*Supported protocols*: NFS, CIFS, iSCSI, and FC

|===
|*Service level* |*Extreme* and *Extreme without Tiering*
(Hot, non-tiered data only) |*Premium* and *Premium without Tiering*
(Hot, non-tiered data only) |*Standard* |*Value*
|*Workload type* |Analytics, databases |VDI, virtualization apps, Software dev
|File shares, web servers |Backup
|*Target IOPS/logical TiB allocated per volume* |6,144 |2,048 |128 |N/A
|*Maximum IOPS/ logical TiB allocated per volume* |12,288 |4,096 |512 |N/A
|*Maximum MBps (throughput)/logical TiB allocated per volume* |384 |128 |16 |N/A
|*Average Latency* |<1 ms |<2 ms |<17 ms |N/A
|*Block size* 
4+|32K 
.2+|*Minimum capacity*^1,2^
4+|100 TiB^1^
|15 TiB^2^ |25 TiB^2^ |50 TiB^2^ |50 TiB^2^

|===

[NOTE]
^1^ Minimum one-year term and 100TiB minimum capacity for a combination of any file share and block service levels for NetApp direct opportunities.
^2^ Minimum one-year term and minimum stated capacity per each service tier selected for channel led opportunities.

=== Block storage
*Supported protocols*: FC and iSCSI

|===
|*Service level* |*Extreme* |*Premium* |*Standard*
|*Workload type* |HPC |Video surveillance |Backup
|*Target IOPS/TiB*
3+|N/A
|*Max IOPS/TiB* |5.500 |4,000 |N/A
|*Max throughput MBps (32KB/IOP)* |43 |31 |N/A
|*Latency* |<0.5 ms |<0.5 ms |N/A
|*Minimum capacity*^1,2^ |100 TiB^3^ |100 TiB^3^ |300 TiB^3^
|===

[NOTE]
^1^ Minimum one-year term and 100TiB minimum capacity for a combination of any file share and block service levels for NetApp direct opportunities.
^2^ Minimum one-year term and minimum stated capacity per service tier selected for channel led opportunities.
^3^ Minimum one-year term and minimum stated capacity per service tier selected for either opportunity type.

=== Object storage
*Supported protocol*: S3

|===
|*Service level* | Object
|*Workload type* |Media repository, archiving
|*Target IOPS/TiB*
|N/A
|*Max IOPS/TiB* |N/A
|*Max throughput MBps (32KB/IOP)* |N/A
|*Latency* |N/A
|*Minimum capacity*^1,2^ |500 TiB^3^

|===

[NOTE]
^1^ Minimum one-year term and 100TiB minimum capacity for a combination of any file share and block service levels for NetApp direct opportunities.
^2^ Minimum one-year term and minimum stated capacity per service tier selected for channel led opportunities.
^3^ Minimum one-year term and minimum stated capacity per service tier selected for either opportunity type.

You can assign service levels to your subscriptions from multiple screens of the NetApp Service Engine user interface. For more information, see link:nkfsosm_tenancy_overview.html[Tenancy and multi-tenancy in Keystone].

=== More on service levels

The performance characteristics specified in the previous sections are subject to the following conditions:

* The service levels for file and block storage support ONTAP 9.7 and later.
* IOPS/TiB/volume, MBps/TiB/volume, and latency values for service levels are based on the amount of logical data stored in the volume, 32KB block size, and a random combination of 70% read and 30% write IO operations. 
* Actual IOPS/TiB/volume and MBps/TiB/volume may vary based on the actual or assumed block size, system workload concurrency, or IO operations.
* Latency does not include application, host, customer network latency to or from the controller ports, overheads associated with the data transfer to the object store in case of FabricPool, or latency automatically applied by QoS to keep IO within service level maximums.
* Latency values are not applicable to MetroCluster write operations. These write operations are dependent on the distance of remote systems.
* If one or more volumes on a storage system do not have an AQoS policy assigned, then these volumes are considered as non-compliant volumes, and no target service levels are applicable for those systems.  
* Expected IOPS is targeted for FabricPool only if the tiering policy is set to "none" and no blocks are in the cloud. Expected IOPS is targeted for volumes that are not in a SnapMirror synchronous relationship.
* Workload IO operations need to be balanced across all deployed controllers, as determined by the Keystone order.

