---
sidebar: sidebar
permalink: nkfsosm_performance.html
keywords: netapp, keystone, performance, service levels
summary: Keystone performances service level
---

= Service levels
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:47.987174
//

[.lead]
Keystone offers data storage capacity at pre-defined performance service levels (service levels) or rate plans on a subscription basis. Each volume managed by the Keystone services is associated with a service level.

Each service level is defined by its I/O density, that is IOPS/TiB/volume. This is the ratio of performance (input/output operations per second [IOPS]) and allocated storage capacity (TiB) which is IOPS/TiB at average latency per volume.

The I/O density for a volume is calculated at an hourly interval to report the peak I/O density. I/O density reports for volumes are generated monthly.

You select service levels based on your storage environment, and storage and consumption needs. The base service levels are available to you by default. Specific service levels are additionally available, if you have opted for other services. For example, for the data protection service, a specific _Data-Protect <base-service-level>_ service level is assigned to your subscription.

The base service levels for file, block, and object storage types are listed here.

== Service levels for file storage
*Supported protocols*: NFS, CIFS, iSCSI, and FC

|===
|*Service level* |*Extreme* |*Premium* |*Standard* |*Value*
|*Workload type* |Analytics, databases |VDI, virtualization apps, Software dev
|File shares, web servers |Backup
|*Maximum IOPS/logical TiB allocated per volume* |12,288 |4,096 |512 |N/A
|*Target IOPS/logical TiB allocated per volume* |6,144 |2,048 |128 |N/A
|*Maximum MBps/logical TiB allocated per volume* |384 |128 |16 |N/A
|*Average Latency* |<1 ms |<2 ms |<17 ms |N/A
|*Block size* 
4+|32K
|===

=== More on service levels for file storage

The base service level metrics depend on the following conditions:

* The service levels for file and block storage support ONTAP 9.7 and later.
* IOPS/TiB/volume, MBps/TiB/volume, and latency values for service levels are based on the amount of logical data stored in the volume, 32KB block size, and a random combination of 70% read and 30% write IO operations.
* Actual IOPS/TiB/volume and MBps/TiB/volume may vary based on the actual or assumed block size, system workload concurrency, or input-output operations.
* Latency does not include the following: 
** application or host latency
** customer network latency to or from the controller ports
** overheads associated with the data transfer to the object store in case of FabricPool
** latency automatically applied by QoS to keep IO within service level maximums
* Latency values are not applicable to MetroCluster write operations. These write operations are dependent on the distance of remote systems.
* If one or more volumes on a storage system do not have an AQoS policy assigned, then these volumes are considered as non-compliant volumes, and no target service levels are applicable for those systems.
* _Expected IOPS_ is targeted for FabricPool only if the tiering policy is set to "none" and no blocks are in the cloud. _Expected IOPS_ is targeted for volumes that are not in a SnapMirror synchronous relationship.
* Workload IO operations need to be balanced across all deployed controllers, as determined by the Keystone order.

== Service levels for block storage
*Supported protocols*: FC and iSCSI

|===
|*Service level* |*Extreme* |*Premium* |*Standard*
|*Workload type* |HPC |Video surveillance |Backup
|*Target IOPS/TiB*
3+|N/A
|*Max IOPS/TiB* |5,500 |4,000 |N/A
|*Max throughput MBps (32KB/IOP)* |43 |31 |N/A
|*Average Latency* |<0.5 ms |<0.5 ms |N/A
|*Block size* 
3+|32K
|===

== Service levels for object storage
*Supported protocol*: S3

|===
|*Service level* | Object
|*Workload type* |Media repository, archiving
|*Target IOPS/TiB*
|N/A
|*Max IOPS/TiB* |N/A
|*Max throughput MBps (32KB/IOP)* |N/A
|*Average Latency* |N/A

|===


