---
sidebar: sidebar
permalink: nkfsosm_netapp_service_engine.html
keywords:
summary:
---

= NetApp Service Engine
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:48.238029
//

[.lead]
The NetApp Service Engine web portal provides the means to manage and monitor a NetApp Keystone subscription storage service in a NetApp-, partner-,  or customer-operated model. The portal consists of the following features (Figure 8):

* A graphical interface (NetApp Service Engine web interface) that supports monitoring and simple storage provisioning.
* A set of Keystone REST APIs that allow more advanced setup and storage management actions.

image:nkfsosm_image9.emf[Error: Missing Graphic Image]

The NetApp Service Engine portal is a single interface that allows customers to perform the following tasks:

* Subscription dashboard. View status of subscribed capacity and how much is being consumed.
* Storage provisioning. Workflows to create your NFS/CIFS file shares, FC/iSCSI disks,  and S3 bucket.
* Data protection. Create snapshots and set backup policy or data replication on the provisioned file share or disk.
* Reports. View file shares and disks inventory and also trend on capacity usage against different service levels.
* Manage subscription. Order additional capacity to an existing subscription or a new service through the portal.
* Submit service requests or support issues and view their status


