---
sidebar: sidebar
permalink: nkfsosm_site_requirements.html
keywords: netapp, keystone, sire, requirements,
summary: Keystone site requirements
---

= Site requirements
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:48.281710
//
[.lead]
There are multiple requirements for enabling NetApp Keystone services in your environment, such as space, racks, PDUs, power, and cooling, with additional network and security requirements discussed later.

== Space
Floor space to host the Keystone infrastructure equipment (to be provided by customers). NetApp provides the weight specifications based on the final configuration.

== Racks
Four post racks in the customer-operated offering (to be provided by customers). In the NetApp-operated offering, either NetApp or the customer can provide the racks, depending on requirements. NetApp provides 42 deep racks.

== PDUs
You should be providing the power distribution units (PDUs), connected to two separate, protected circuits with sufficient C13 outlets. In the customer-operated offering, in some cases, C19 outlets are required. In the NetApp- operated offering, either NetApp or the customer can provide the PDUs, depending on requirements.

== Power
You should provide the required power. NetApp will provide the power requirement specifications based on 200V rating (Typical A, Max A, Typical W, Max W, Power cord type, and quantity), based on the final configuration. All components have redundant power supplies. NetApp will provide the in-cabinet power cords.

== Cooling
NetApp can provide the cooling requirement specifications (Typical BTU, Max BTU), based on the final configuration and requirement.

== Networking
Depending on customer requirements and the storage controllers used, NetApp can provide 10 Gib, 40 Gib, and 100 Gib connectivity at the customer site.

NetApp provides the required transceivers for NetApp-provided Keystone infrastructure devices only. You should supply transceivers required for customer devices and cabling to the NetApp-provided Keystone infrastructure devices.
