---
sidebar: sidebar
permalink: nkfsfaq_overview.html
keywords: netapp, keystone, overview,
summary: NetApp Keystone Overview
---

= NetApp Keystone frequently asked questions (FAQs)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following questions give answers to your frequent queries about NetApp Keystone.

*What is NetApp Keystone?*

NetApp Keystone is a portfolio of on-premises capital expenditure (CapEx) alternatives.
For more information, see https://www.netapp.com/services/keystone/[NetApp Keystone^].

*How does NetApp Keystone benefit my customers?*

NetApp Keystone is the bridge that connects the pillars of our CapEx and hybrid cloud strategy— delivering agility, financial flexibility, and reduced financial risk that helps customers meet their cash flow and business needs.

The NetApp Keystone brand offers a portfolio of flexible payment solutions that include traditional financing, leasing, and fixed/variable options for cash-conscious customers along with Keystone services.

*Keystone services (OpEx, cloud-like experience):*
* Prefer 100% OpEx, so assets will not end up on your customer’s balance sheet
* Internal/external Service Providers looking to align costs with usage/revenue
* Workloads with unpredictable capacity growth
* Reallocated IT resources from typical storage tasks (migrations, tech refresh, upgrades, and so on)
* Short-term solution before migrating workloads to the cloud
* Repatriating workloads back from the cloud to on- premises

*What is NetApp Keystone?*

NetApp Keystone is a new, flexible, on-premises subscription-based procurement model. It enables customers to accelerate time to value by removing the hurdles around managing the resources and going through the lengthy procurement cycle. Keystone services allow customers to align economics to their business priorities.
For more information, see link:https://docs.netapp.com/us-en/keystone/index.html#netapp-keystone-flex-subscription[here].

*What does on-premises mean?*

On-premises is defined as a customer-owned data center or customer-owned space in a colocation facility. The customer is responsible for the space, power, and cooling.

*What are the benefits of Keystone services?*

Some benefits of Keystone services are:

* Frees up IT staff from complicated storage-related tasks and allows them to focus on application management
* Reduces upfront capital investment
* Allows customers to meet their demands without overprovisioning
* Aligns data storage costs with business needs/activity
* Simplifies infrastructure provisioning by bypassing complex organizational procurement procedures
* Keeps data secure on their premises
* Enables proper control over compliance, performance, and security
For more information, see link:https://docs.netapp.com/us-en/keystone/index.html#benefits-of-flex-subscription[here].
