---
sidebar: sidebar
permalink: nkfsosm_keystone_infrastructure.html
keywords:
summary:
---

= Keystone Infrastructure
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:48.261549
//

[.lead]
This section describes the infrastructure components used in the customer- and NetApp-operated offerings. The components are also classified based on whether they reside in the data versus control plane that serve to segregate user data from command and control data.

|===
|Component |Plane |Operation Model |Purpose

|Storage controllers
|Data
|Customer and NetApp/partner
|Provides storage capacity for KFS
NetApp AFF and FAS controllers are used based on capacity and performance service level requirements.

|Cluster switches
|Data
|Customer and NetApp/partner
|Provides cluster traffic pathway among three or more storage controllers. If the configuration consists of two controllers, then switchless cluster configuration is used.
|Data switches
|Data
|NetApp/partner only
|Data connectivity between user and KFS storage.
Cisco Nexus 9K switches are selected to provide enough ports for KFS storage controllers and customer data network connectivity providing bandwidth and flexibility to provide 10/25/50/100 GbE connectivity.
|Management switches
|Control
|NetApp/partner only
|KFS devices’ management port connectivity.
Cisco Nexus 9K 1 GbE switches are selected to provide enough ports to attach to the devices’ management ports, as well provide 10GbE data connectivity to the management servers and storage.
|Firewalls
|Control
|NetApp/partner only
|Limit access to and protect KFS management network and KFS components.
Palo Alto firewalls are selected to provide segregation of the KFS management network from the customer network.
|Management servers
|Control
|NetApp/partner only
|Executes KFS monitoring and management applications: NetApp Service Engine API, NetApp Service Engine GUI, OpsRamp, Active IQ Unified Manager.
|Management storage
|Control
|NetApp/partner only
|Provides shared storage for management servers and applications.
Small NAS-based storage system is selected to meet the requirements of NetApp Service Engine.
|Console switch
|Control
|NetApp/partner only
|Provides serial console access to KFS devices.
|===
