---
sidebar: sidebar
permalink: nkfsosm_data_protection.html
keywords: netapp, keystone, data, protection,
summary: Data protection
---

= Data protection
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:48.048848
//

[.lead]
NetApp Keystone data protection service can back up your data and is able to recover it if required. The available data protection services are:

* Snapshots of disks and shares
* Backups of disks and shares (requires data protection service as part of the subscription)
* Disaster recovery for disks and shares (requires data protection service as a part of the subscription)

[NOTE]
Backup and disaster recovery services are available as add-on services, while snapshot is available as a part of the basic storage service.

If you have subscribed to data protection services, specific service levels are assigned to your subscriptions, for example _Data-Protect Extreme_, _Data-Protect Premium_, and so forth. For information, see https://docs.netapp.com/us-en/keystone/aiq-keystone-details.html#reference-charts-for-data-protection[Reference charts for data protection].

|===
| |Single Region snapshots (Available as a part of the basic storage service) |Multi-region Backup (data protection add-on) |Multi-region Disaster Recovery (data protection add-on)

|Use case
|Mitigate the risk of user or application data deletion or corruption, not against infrastructure loss or failure
|Mitigate the risk of complete loss of data on the primary volume due to infrastructure loss or failure
|Mitigate the risk of complete loss of data on the primary volume due to infrastructure loss or failure with a recovery time objective
|Policy
|Hourly, daily, weekly, and monthly
|Number of backups to retain based on hourly, daily, weekly, and monthly snapshots
|1 hour, 4 hours, and daily
|Topology
|Source only
|Backup
|Async replication target
|Target replication service level^1^
|n/a
|Standard
|Same as primary
|===
^1^Additional storage capacity to be subscribed

[NOTE]
Subscription to a basic Keystone service does not automatically back up your data. You should subscribe to add-on data protection services and configure your system for data backup and disaster recovery services. If your storage system is not managed by Keystone services, NetApp can still support protecting the data on your storage system and help in connecting it with your Keystone services. However, NetApp is not responsible for any backup failures.
