---
sidebar: sidebar
permalink: nkfsosm_release_management.html
keywords:
summary:
---

= Release Management
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:48.901923
//

[.lead]
NetApp provides release management services to ensure the secure, controlled deployment of releases into the customer’s supported environment in accordance with the NetApp release management and NetApp service methodology. This includes the definition, creation, and documentation of release plans, creation of change requests required for the release plan, ensuring that software and firmware currency is up-to-date and the ongoing reviews of the supported environment.

Release management services include:

* Creating a release plan if requested by the customer.
* Assessing the impact of each release on the managed services; any affected parties of which NetApp is or ought reasonably to be aware, and notifying the customer of those impacts.
* Updating the release plan upon the implementation of all releases.
