---
sidebar: sidebar
permalink: nkfsfaq_operations_and_support.html
keywords: netapp, keystone, operations, support,
summary: Operations and Support
---

= Operations and Support
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:15:37.043322
//

[.lead]
*How do I view the Flex Subscription usage?*
NetApp Service Engine provides a dashboard view, with information on all the services that are subscribed to and how much is consumed. For details about NetApp Service Engine, see link:https://sewebiug_overview.html[here].

*How do I report any issues with the service?*
NetApp Keystone support can be reached through these various channels:

* Support email: mailto:keystone.services@netapp.com[keystone.services@netapp.com^]
* Escalations email: mailto:keystone.escalations@netapp.com[keystone.escalations@netapp.com^]

*Can I order new storage service?*
Yes, new storage service or expansion to storage service can be requested from the NetApp Service Engine portal. The request is processed by the NetApp Keystone operations team before making it available for use.

*Are increases to storage commitments available immediately?*
Depending the amount of capacity requested, a determination is made whether the capacity is already deployed, or it requires additional equipment to be shipped and installed.

*Can workloads be moved between the tiers?*
Yes, workloads can be moved between tiers, provided the user has subscribed to the tier the workload is moving to. However, we do not recommend moving from a higher tier to a lower tier because it can cause a performance degradation. The process is achieved by simply editing the file share and changing the service level setting.

*What software version (for example, ONTAP) is installed as default?*
Depending on the service tier subscribed (for example, ONTAP with File and Block services, SANtricity for Block, and StorageGrid for Object) the support team installs the latest stable release with no security or feature issues.

*Can I request a particular software version?*
No. NetApp Keystone has standardized the software version across all its customer base.

*Will I be informed about software upgrades?*
Yes. All maintenance/upgrade activities are communicated to and scheduled at a mutually agreeable time with the customer by the NetApp Keystone Success Manager.
