---
sidebar: sidebar
permalink: nkfsosm_system_expansion.html
keywords:
summary:
---

= System Expansion
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:48.956222
//

[.lead]
NetApp will deploy the initial system based on current and future anticipated capacity and performance requirements and outlook, in addition to certain assumptions, such as the data efficiencies factor. This is to ensure sufficient infrastructure is being deployed to avoid adding additional infrastructure soon thereafter.

Although there are no specific thresholds that trigger an automatic controller or disk/SSD additions, capacity consumption and performance levels are monitored and alerts are provided to the KSM starting at 70% of provisioned committed capacity and at 60% of physical usable capacity, or 80% of controller utilization. KSM determines if additional infrastructure must be deployed to deliver contracted capacity and performance; if so, KSM initiates the add capacity/performance process.

Alternatively, a customer might request an increase to the committed capacity through the NetApp Service Engine portal. If additional capacity at the requested performance level can be made available based on existing deployed equipment, it will be enabled for use; otherwise, KSM will initiate the add capacity/performance process.  


