---
sidebar: sidebar
permalink: nkfsfaq_keystone_subscription.html
keywords:
summary:
---

= Keystone Subscription
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:15:36.922050
//

[.lead]
*What is the minimum committed capacity?*

The minimum committed capacity for a NetApp Keystone Subscription is 100 TiB, per site across one or more service tiers.

*What does a NetApp Keystone subscription map to?*

A NetApp Keystone Subscription maps to a single site or a single data center and it can comprise of different performance service levels.

*How does the customer increase the committed capacity in a subscription?*

Customers can submit a capacity addition request through the NetApp Service Engine management tool or through their NetApp Keystone success manager.

*Does increasing the capacity extend the term?*

All the additions are co-term to the existing term period, except if the request is made in the last 90 days of the subscription, in which case the term must extend for at least 12 months.

*Does a new subscription have flexibility to come with a new yearly term?*

Yes, new subscriptions can have new terms separate from any existing subscriptions.

*Can a customer mix multiple subscriptions on the same ONTAP cluster?*

No, each cluster is assigned to a particular subscription.

*Can the customer reduce the committed capacity?*

No. During a term, the committed capacity can only be increased but not decreased.

*What is burst capacity?*

The customer can increase and decrease usage up to 20% above the committed capacity. The burst capacity usage is measured on a daily basis and billed only when used.

For example, if the committed capacity is 100 TiB, customers can burst up to 120 TiB.

*Is there a premium charge for using burst?*

The burst capacity usage up to 20% of committed capacity is billed at the same rate as committed capacity, any usage above 20% of committed capacity is billed at 50% premium.

*What is the benefit of burst capacity?*

Burst capacity gives the customer flexibility to consume storage on demand versus committing for the long term.

*Where can the customer see the committed and burst capacity usage?*

NetApp Service Engine has built-in dashboards to report consumed capacity against committed capacity.

*Will there be any notifications if the customer reaches a certain percentage in committed capacity usage?*

Yes, the management tools provide notifications on capacity usage through the NetApp Service Engine dashboard.
