---
sidebar: sidebar
permalink: nkfsosm_change_management.html
keywords: netapp, keystone, change, management,
summary: Change management
---

= Change Management
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:48.878850
//

[.lead]
To manage changes to the NetApp Keystone Storage Platform, the following NetApp Change Management process is followed. The table below lists the risk levels and lead times.

* NetApp KSM coordinates with customer change management to review or approve changes.
+
However, in the case of customer management seeking more information about an upcoming change, an escalation path is available to customer management.

* A change management request originating from NetApp to the customer representative (excluding emergency changes) at a minimum includes:
** Detailed description of the scope of the change, including benefits, risks, and any outage
** Any dependencies
** List of resources required to successfully implement the change
** Proposed schedule, including implementation duration and dates
** Comprehensive contingency plan, including back-out strategy
* If a customer does not allow NetApp to perform mandatory or critical maintenance activities, then NetApp reserves the right to discontinue affected services, SLAs, and be absolved of any consequential damages, responsibilities, and penalties resulting from not being allowed to perform these activities.
* In the event of an emergency change, NetApp Keystone Operational Services and KSM performs the change on the platform and the team informs the customer as early as possible if there is a possibility of impact to the customers.

|===
|Risk Level |Description |Lead Time

|5
|Outage to customer or business services
|15 business days
|4
|Change can have an impact to customer’s business or services in under 10 minutes
|5 business days
|3
|No impact; large/medium risk change
|3 business days
|2
|No impact; small risk change
|1 business days
|1
|Not in use for IT
|n/a
|===
