---
sidebar: sidebar
permalink: nkfsosm-keystone-and-aiq.html
keywords: netapp, keystone, aiq keystone customers, Active IQ, Digital Advisor
summary: what can customers see in Active IQ for keystone
---

= What can Flex Subscription customers view in Active IQ Digital Advisor?
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
If you have subscribed to NetApp Keystone Flex Subscription (Flex Subscription) services, you can view your usage reports and graphs on the Active IQ Digital Advisor (Digital Advisor) dashboard.

For more information about Digital Advisor, see link:https://docs.netapp.com/us-en/active-iq/index.html[Digital Advisor documentation].

If your site has NetApp Service Engine installed by default, you can view the consumption charts through the NetApp Service Engine interface in addition to Digital Advisor. However, in a customer-managed environment, you do not have access to the NetApp Service Engine interface, and you can view your capacity charts and usage reports only through the Digital Advisor dashboard.
For information about customer-managed environments, see https://docs.netapp.com/us-en/keystone/nkfsosm_overview.html[Operational model, roles, and responsibilities]

The interval of metrics data collection from your site is 5 minutes.

As a customer, if you have subscribed to the Flex Subscription services, you can view the following information on Digital Advisor: 

* *Keystone Flex Subscription* widget: If you have logged in to Digital Advisor, you can see the *Keystone Flex Subscription* widget that summarizes the capacity usage against your purchased Flex Subscription services.

For more information, see link:https://docs.netapp.com/us-en/active-iq/view_keystone_capacity_utilization.html[View capacity utilization with NetApp Keystone Flex Subscription].

For information about the *Keystone Subscriptions* tab, see _Digital Advisor dashboard and reporting for Flex Subscription_.
