---
sidebar: sidebar
permalink: nkfsosm_where_to_find_additional_information.html
keywords: netapp, keystone, where, find, additional, information,
summary:
---

= Additional Information and Support Contact
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:49.033958
//

[.lead]
You can contact the support desk and find additional documentation in the following sections.

* Global Service Contacts :
https://www.netapp.com/us/contact-us/support.aspx

* NetApp uses OpsRamp, a cloud-based remote gateway solution to proactively monitor and connect to the Keystone environment for troubleshooting purposes. For information on OpsRamp, see https://www.opsramp.com/#.

* If you have an open case/ticket that needs to be escalated, please send an email to one of the following addresses:
Keystone.services@netapp.com
Keystone.escalations@netapp.com

To learn more about the information that is described in this document, review the following documents and/or websites:

* NetApp Keystone
 https://www.netapp.com/us/solutions/keystone/index.aspx[https://www.netapp.com/us/solutions/keystone/index.aspx^]
* NetApp Product Documentation
 https://docs.netapp.com[https://docs.netapp.com^]
