---
sidebar: sidebar
permalink: nkfsosm_keystone_service_capacity_definitions.html
keywords: netapp, keystone, service, capacity, definitions, burst, committed capacity, consumed capacity, billed capacity
summary: Keystone service capacity definitions
---

= Flex Subscription service capacity definitions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:47.956229
//

[.lead]
The NetApp Keystone Flex Subscription (Flex Subscription) service capacities include:

== Logical capacity
This is the data placed into the Flex Subscription infrastructure by a customer. All Flex Subscription capacities refer to a logical capacity.
For example, if a 1 TiB file is stored on the Flex Subscription infrastructure, then at least 1 TiB of capacity must be purchased.

== Committed capacity
The minimum logical capacity billed each month for the duration of the term:

** Capacity is committed to each service level.
** Committed capacity cannot be decreased during the term.
** Committed capacity and additional service levels can be added during the term.

=== Changes to committed capacity
During the tenure of a subscription, you can change the committed capacities. However, there are certain preconditions:

*	The committed capacity cannot be decreased
*	The committed capacity cannot be increased 90 days prior to the expiry of your subscription, unless the subscription is to be renewed for an additional 12 month term.
* You can request changes to committed capacity through the NetApp Service Engine interface or through Keystone Success Manager.
For information about requesting changes, see link:sewebiug_raise_a_service_request.html[Raise a service request].

== Burst capacity
This is the logical capacity that has exceeded the committed capacity. Note the following points:

** Flex Subscription service provides 20% capacity in excess of the committed capacity.
** Burst capacity can be consumed on an elastic basis and is charged on a daily basis of the consumed average.
** Burst capacity up to 20% is charged at a same rate as the committed capacity.
** Burst capacity greater than 20% of committed is charged at a premium rate. Contact support for any additional burst requirements greater than 20%.

== Consumed/provisioned capacity
Consumed capacity refers to the capacity in TiB of storage currently being consumed on the service. Flex Subscription service considers the sum of the provisioned sizes (not the logical or physical capacity used) of all volumes on a particular service level to be considered as consumed capacity for that service level. This includes:

** The capacity that is provisioned through the creation, modification, deletion, or potential auto-growth of volumes.
** The Snapshot copies and clones.
[NOTE]
The amount of data stored within provisioned capacity, or the amount of data actually written to disk is not considered.

== Billed capacity
Monthly bill = (committed capacity [TiB] * committed rate [$/TiB]) + (daily average provisioned burst capacity [TiB] * burst rate [$/TiB]). The monthly bill contains a minimum charge based on the committed capacity.

The monthly bill varies beyond the minimum charge based on daily average burst capacity consumption.
For more information on billing, see link:nkfsosm_kfs_billing.html[Flex Subscription billing].
