---
sidebar: sidebar
permalink: nkfsosm_kfs_billing.html
keywords: netapp, keystone, billing, Keystone billing logic, charges, charging, billing cycle, billing schedule, MetroCluster billing, TMP temporary volumes, Adaptive QoS policy billing, cloned volumes, burst billing
summary: Keystone billing
---

= Keystone billing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/


[.lead]
NetApp Keystone enables predictable and upfront pricing for your storage subscription.

If you prefer operational expenditures (OpEx) consumption model to capital expenditure (CapEx) or leasing, you can opt for the Keystone pay-as-you-grow model for your flexible and scalable consumption needs.

Keystone provides you with the following billing facilities:

* You can pay based on IOPS and latency committed capacity to meet various workload needs. The different performance service tiers - Extreme, Premium, Standard, and Value enable you to manage your storage based on your purchased service level for your Keystone services.
* It presents predictable billing for the committed capacity and pay-per-use for variable (burst) capacity usage.
* You can select a bundle price for hardware, core OS, and support for one $/TiB price. You have a single invoice for each storage type, file, block, object, or cloud storage services.
* Select a flexible term for the services and payment: You can opt for 12 months, 100TiB, or more per site. Thereafter you can auto renew for 12 months or go month-to-month.

Keystone billing is based on committed capacity and variable burst consumption.

For information about committed and burst capacity usage, see link:nkfsosm_keystone_service_capacity_definitions.html[Keystone service capacity definitions].

For information about how to view billing details, see link:sewebiug_billing.html[View billing].

== Billing based on committed capacity
Committed capacity refers to the capacities for various services in a single subscription, agreed upon by the parties involved (NetApp/partner and customer). This capacity is stated on each Keystone order and is billed, regardless of the actual consumption.

.Metering of consumed capacity
As a part of the Keystone service deployment, NetApp continuously monitors and measures the consumption of the service. Every five minutes, a consumption record is generated by the system, detailing the current consumed capacity for the subscription. These records are aggregated over the billing period to generate invoices and usage reports.

== Billing based on burst consumption
When the consumed capacity is greater than the committed capacity for a given service level, burst consumption is recorded, and charges are applied accordingly. This process occurs for each consumption record generated. Burst consumption, therefore, is a reflection of both the amount and tenure of your over-consumed capacities on top of your committed capacities.

== Billing schedules
Keystone services are billed monthly and yearly.

.Monthly billing
Invoices are sent monthly. For the month in which the services are availed, an invoice is sent in the next month. For example, the invoice for the services you have used in January is delivered at the beginning of February. This invoice includes the charges for the committed capacity and if applicable, any burst usage.

.Annual billing
An invoice is generated at the beginning of each subscription year for the minimum payment of the committed capacity. It is generated on the start date of the subscription.
Another invoice is sent at the end of a subscription quarter, summing up the applicable charges of any burst usage accrued in that quarter.
If the committed capacity is changed during a subscription, then an invoice is sent on the same day the change in the committed capacity is effective, for the prorated minimum payments for the rest of that subscription year.

.Grace period in burst billing
During the first 60 days of the activation of a subscription, any burst consumption that you accrue is recorded, but not charged on your Keystone service invoice. This grace period grants you the time to configure your storage with the appropriate Adaptive Quality of Service (AQoS) settings so that it can be properly monitored and billed. On configuring your storage correctly, you can avoid any unexpected burst charges. Any burst usage accrued after the initial grace period of 60 days will be billed on your next invoice. This grace period does not affect any modifications or renewals to your existing subscriptions.

== Miscellaneous scenarios for Keystone billing
There are several scenarios for Keystone billing and you should be familiar with those scenarios.

=== Billing for cloned volumes
If volumes are cloned in ONTAP and you use them for backing up and restoring your data, you can continue using the clones without any additional payments. However, cloned volumes used for any other purpose in your business for an extensive duration are charged.

Note the following:

* The consumption on the cloned volumes is not considered during the first 24 hours of the clone creation; and no charges are incurred during this time.
*	Cloned volumes with the Standard and Value service levels are not considered for consumption, if new data is not written to the volume. For example, in a backup or restore use case, backing up or restoring data from a cloned volume does not change the data in the cloned volume itself, and it is not considered as consumption.

=== Billing for MetroCluster
Advanced Data Protection uses NetApp MetroCluster to mirror data between two physically separated clusters. On MetroCluster mirrored aggregates, data is written twice, once on each cluster. Keystone service charges for consumption on each side independently, resulting in two identical consumption records.
If you monitor your clusters through ONTAP System Manager (System Manager) or Active IQ Unified Manager (Unified Manager), you might see a discrepancy between the consumption reported on these tools and Keystone services. System Manager and Unified Manager do not report volumes on the mirrored (remote) cluster, and in doing so, reports half the consumption metrics that the Keystone service reports.

For Example:
Site A and Site B are set up in a MetroCluster configuration. When a user creates a volume of 10TB in site A, an identical volume of 10TB is created in site B. Keystone distinguishes both the volumes and records an additional 10TB of consumption in each site, for a total increase of 20TB. System Manager and Unified Manager reports a 10TB volume created in site A.

=== Billing for temporary volumes
Occasionally, temporary (TMP) volumes are created by ONTAP when moving volumes. These temporary volumes are short-lived, and the consumption on these volumes is not measured for billing.

=== Billing and adaptive QoS policies
Keystone measures consumption based on service levels. Each service level is associated with a specific adaptive quality of service (QoS) policy. During deployment, you will be informed of the details of each QoS policy for your subscribed Keystone services. During storage management operations, ensure that your volumes have the appropriate QoS policies assigned as per your subscribed service levels, to avoid unexpected billing.
For more information about QoS policies in ONTAP, see link:https://docs.netapp.com/us-en/ontap/performance-admin/guarantee-throughput-qos-task.html[Guarantee throughput with QoS overview].

=== Billing for SnapMirror destinations
The pricing for the SnapMirror destination volume governed by the QoS policy for the service level assigned on the source. However, if the source does not have an associated QoS policy, the destination is billed based on the lowest available service level.

=== Billing for FlexGroups
FlexGroups are billed based on the adaptive QoS policy of the FlexGroup. The QoS policies of its constituents are not considered.

=== Billing for LUNs
For LUNs, usually the same billing pattern is followed as for the volumes that are governed by QoS policies. If separate QoS policies are set on LUNs, then:

*	The size of the LUN is counted for consumption according to the associated service level of that LUN.
*	The remainder of the space in the volume, if any, is charged according to the QoS policy of the service level set on the volume.

=== Billing for FabricPool usage
If data is tiered from a Keystone system to ONTAP Simple Storage Service (S3) object storage or NetApp StorageGRID, then the consumed capacity on the hot tier (Keystone system) will be reduced by amount of data that has been tiered off, impacting the resultant billing. This is regardless of the fact whether the ONTAP S3 storage or StorageGRID system is covered by the Keystone subscription.

For tiering your data to any third party object storage, contact your Keystone Success Manager.

For information on the use of FabricPool technology for your Keystone subscriptions, see link:nkfsosm_tiering.html[Tiering].

=== Billing for system and root volumes
System and root volumes are monitored as a part of the overall monitoring of the Keystone service but are not counted or billed. The consumption on these volumes is exempted for billing.
