---
sidebar: sidebar
permalink: nkfsosm_keystone_service_delivery_manager.html
keywords: netapp, keystone, service, delivery, manager,
summary: Keystone service delivery manager
---

= Keystone Service Delivery Manager
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-08 17:14:48.578700
//

[.lead]
The KSDM owns Service Delivery Management. The KSDM is responsible for managing the day-to-day administration and operations of the Keystone system. The KSDM’s primary role is to ensure that agreed service levels are being managed and met.

The KSDM owns Service Delivery Management in coordination with the KSM. The KSDM is responsible for managing the day-to-day operations of the Managed Services team as well as being the primary contact for the customer’s stakeholders and NetApp account teams. The KSDM’s primary role is to ensure that agreed Service Levels are being managed and met, service delivery improvements are ongoing, and that the customer/NetApp relationships are maintained.

The KSDM is the primary contact for customer meetings, customer reporting, and customer communication between the customer and the NetApp Managed Services team.

The KSDM is responsible for the following activities during the length of the contract:

* Champions operations and service delivery in accordance with the NetApp service delivery methodology.
* Manages day-to-day activities and priorities for the NetApp operations team (in a NetApp-operated model).
* Is the point of escalation for all critical incidents; keeps account team updated on the operational status with respect to the supported environment.
* Oversees the following reviews:
** Incident review
** Escalation handling
** Capacity review
** Performance review
** Availability review
** Communications
