---
sidebar: sidebar
permalink: nkfsfaq_keystone_subscription.html
keywords: netapp, keystone, subscription, subscriptions,
summary: NetApp Keystone Subscription
---

= NetApp Keystone Flex Subscription
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
*What is the minimum committed capacity?*
The minimum committed capacity for a NetApp Keystone Flex Subscription (Flex Subscription) is 100 TiB, per site across one or more service tiers.

*What does Flex Subscription map to?*
Flex Subscription maps to a single site or a single data center and it can comprise of different performance service levels.

*What are the benefits of extreme-tiering and premium-tiering performance levels?*
Tiering is enabled in the extreme-tiering and premium-tiering performance levels, which enables you to reduce your storage footprint and associated costs. NetApp assumes that 25% of your data is hot, while the remaining 75% is less frequently used or cold, and moves it to cold storage. Additionally, you can check usage reports to understand how frequently data is accessed and enable tiering service based on the information.

*How can I increase the committed capacity in a subscription?*
You can submit a capacity addition request through the NetApp Service Engine management tool or through their NetApp Keystone success manager.

*Does increasing the capacity extend the term?*
All the additions are co-term to the existing term period, except if the request is made in the last 90 days of the subscription, in which case the term must extend for at least 12 months.

*Does a new subscription have flexibility to come with a new yearly term?*
Yes, new subscriptions can have new terms separate from any existing subscriptions.

*Can tenant subscription terms extend beyond the subscription term of the partner?*
Tenant subscriptions can extend beyond the current Flex Subscription term of the partner. A warning will be displayed when subscriptions are created and also in usage reports.

*Can I mix multiple subscriptions on the same ONTAP cluster?*
No, each cluster is assigned to a particular subscription.

*Can partners sell more capacity than they have purchased from NetApp to customers?*
Tenant subscriptions are not limited by the capacity that the partner has purchased. Partners can sell more capacity than they have purchased from NetApp to their customers. The capacity that is in excess of the purchased capacity is referred to as oversubscription.

*Can I reduce the committed capacity?*
No. During a term, the committed capacity can only be increased but not decreased.

*What is burst capacity?*
You can increase and decrease usage up to 20% above the committed capacity. The burst capacity usage is measured on a daily basis and billed only when used.
For example, if the committed capacity is 100 TiB, you can burst up to 120 TiB.

*Is there a premium charge for using burst?*
The burst capacity usage up to 20% of committed capacity is billed at the same rate as committed capacity, any usage above 20% of committed capacity is billed at 50% premium.

*What is the benefit of burst capacity?*
Burst capacity gives you the flexibility to consume storage on demand versus committing for the long term.

*How is burst capacity allocated to tenants?*
Burst capacity is allocated to partners, who further allocate it to their customers based on requirements.

*Where can I see the committed and burst capacity usage?*
NetApp Service Engine has built-in dashboards to report consumed capacity against committed capacity.

*Will there be any notifications if I reach a certain percentage in committed capacity usage?*
Yes, the management tools provide notifications on capacity usage through the NetApp Service Engine dashboard.
