---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: NetApp Keystone services
      url: /index.html
      entries:
        - title: Service terms and description
          url: /nkfsosm_service_terms_and_description_overview.html
          entries:
            - title: Service capacity definitions
              url: /nkfsosm_keystone_service_capacity_definitions.html
            - title: Service levels in Keystone
              url: /nkfsosm_performance.html
            - title: Service level metrics and definitions
              url: /nkfsosm_service_level_metrics_and_definitions.html
            - title: Adaptive Quality of Service in Keystone
              url: /aqos-kfs.html      
            - title: Billing
              url: /nkfsosm_kfs_billing.html
            - title: Data protection
              url: /nkfsosm_data_protection.html
            - title: Tiering
              url: /nkfsosm_tiering.html
            - title: Non-returnable disk
              url: /nkfsosm_nrd.html
            - title: US Citizen Support
              url: /nkfsosm_uscs.html
            - title: Keystone and Equinix
              url: /nkfsosm_equinix.html
        - title: Operational model and responsibilities
          url: /nkfsosm_overview.html
        - title: Tenancy and multi-tenancy
          url: /nkfsosm_tenancy_overview.html
        - title: Keystone infrastructure
          url: /nkfsosm_keystone_service_delivery_architecture_overview.html
        - title: Site requirements
          url: /nkfsosm_site_requirements.html
        - title: Operations
          url: /nkfsosm_netapp_global_services_and_support_center_@gssc@.html
        - title: Keystone and Active IQ Digital Advisor
          url: /nkfsosm-keystone-and-aiq.html
          entries:
            - title: View and generate reports from Active IQ Digital Advisor
              url: /aiq-keystone-details.html
    - title: Release Notes
      entries:
        - title: What's new
          url: /rn_whats_new.html
        - title: Fixed issues
          url: /rn_fixed_issues.html
        - title: Known issues
          url: /rn_known_issues.html
    - title: Keystone subscriptions FAQ
      url: /nkfsfaq_overview.html
      entries:
        - title: Keystone subscriptions
          url: /nkfsfaq_keystone_subscription.html
        - title: Service offer details
          url: /nkfsfaq_service_offer_details.html
        - title: Operating model
          url: /nkfsfaq_operating_models.html
