---
sidebar: sidebar
permalink: rn_whats_new.html
keywords: netapp, keystone, release notes, new features, what's new,
summary: new features in NetApp Service Engine
---

= What's new in this release of NetApp Keystone Flex Subscription services
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following feature has been introduced in NetApp Service Engine 2.7 to support enhanced services of NetApp Keystone Flex Subscription (Flex Subscription):

== Features introduced in NetApp Service Engine 2.7

The new features in this release include the following:

=== Ability to view your Cloud Volumes ONTAP usage and billing through Flex Subscription

If you are a NetApp Keystone Flex Subscription customer, and also have Cloud Volumes ONTAP subscription, you can use Flex Subscription to charge your Cloud Volumes ONTAP usage and view your billing and consumption details. Cloud Manager can now discover your Flex Subscription accounts and display the details on the Cloud Manager interface. On clicking the *All Services > Digital Wallet > Keystone Flex Subscription* tab, you can perform the following activities:

* View a welcome screen from which you can request your Flex Subscription administrator to associate your Cloud Manager user ID with your Flex Subscription user ID; and thereby gain access to the *Keystone Flex Subscription* tab.
* View the consumption data of the committed and consumed capacities of the subscribed services on your on-premise systems and Cloud Volumes ONTAP.
* View the Flex Subscription details associated with your Cloud Manager account. Details, such as committed, consumed, and burst capacity are displayed.
* Link your Cloud Volumes ONTAP account with your Flex Subscription IDs to associate the account for billing and capacity usage reports.
* Request increasing or decreasing the committed capacity for the subscribed Flex Subscription services.
* View and use the linked Flex Subscription ID as a charging method for billing the Cloud Volumes ONTAP consumption (only linked IDs).

For more information, see the following links in the Cloud Manager documents:
link:https://docs.netapp.com/us-en/occm/concept_licensing.html#keystone-flex-subscription[Keystone Flex Subscription]
link:https://docs.netapp.com/us-en/occm/task_managing_licenses.html#manage-keystone-flex-subscriptions[Manage Keystone Flex Subscriptions]


[NOTE]
The released version of NetApp Keystone Flex Subscription 2.7 is the major release after release 2.2. The internal releases between 2.2 and 2.7 have only minor fixes.


=========================================================================
=========================================================================

== Features introduced in NetApp Service Engine 2.2
The new features in this release include a revamped dashboard for new widgets on billing, capacity utilization, service requests, and alerts. This release also includes new screens for billing and alerts management, and renaming of the Subscribed Services menu to Cloud Services.

=== Enhanced dashboard view
The NetApp Service Engine dashboard has been redesigned to include the following new components:

* *Capacity Utilization* For viewing the utilized capacity for your subscribed services.
* *Monthly Charges (Billing)* For viewing the aggregated monthly charges for all your subscriptions.
* *Alerts*  For viewing the summary of the most recent alerts in your environment.
* *Service Requests* For viewing the list of the most recent service requests generated in your environment.
For more information, see link:sewebiug_dashboard.html[View Flex Subscription Dashboard].

=== New Billing screen
A new *Billing* screen has been added for easy accessibility and calculation of your historical billing data. The screen provides a holistic view of the monthly charges associated with all your subscribed services.

Navigate to this screen from the *Monthly Charges* widget on the dashboard or from *ADMINISTRATION > Billing* to view a monthly, subscription-level break up of the charges for all your subscribed services. The billing data is based on your committed and burst capacity usage, and is available for your usage in the previous months.
For more information, see link:sewebiug_billing.html[View billing].

=== New Alerts screen
A new *Alerts* screen is introduced in this release that lists all system-generated and user-generated alerts. The screen also enables you to create custom alert messages for critical events concerning your environment and convey them to other users. They can view and dismiss the alerts, as required.
For more information, see link:sewebiug_alerts.html[Create and manage alerts].

=== Enhanced user interface
The following enhancements have been made on the NetApp Service Engine user interface:

* The *Dashboard* menu on the left navigation pane presents an intuitive navigation point to access the dashboard.
* The *Subscribed Services* menu on the left navigation pane has been renamed to *Cloud Services*.


===============================================================================
===============================================================================



== Features introduced in NetApp Service Engine 2.1
The new features in this release include supporting multi-tenancy in a Flex Subscription environment, and tiering capability that facilitates moving of inactive data to a lower cost local or cloud tier.

=== Introducing Flex Subscription services for service providers

NetApp Service Engine now supports the management of a multi-tenant environment by a service provider. You can perform the functions of provisioning, reporting, billing, and managing customers having their own subscriptions. For supporting this feature, the following enhancements have been made:

* *Dashboard:* The Dashboard displays information on the storage subscriptions, such as service tiers, capacity usage for each service level, and add-on data protection services, for a specific subscription number. As a service provider, you can view the details of your NetApp Keystone Flex Subscription and tenant subscriptions. As a tenant administrator, you can view the details of all the tenant subscriptions for your tenancy.
* *Reporting:* You can create capacity and performance reports with respect to your NetApp Keystone Flex Subscription usage and also for your tenant usage. As a partner administrator, you can view the capacity report for your Flex Subscription usage from *Reports* > *Keystone Usage*. As a partner admin, you can view the capacity usage reports for a specific tenant from *Reports* > *Tenant Usage*/*Capacity Usage*. As a tenant administrator, you can view the tenancy reports from *Reports* > *Tenant Usage*.
* *Subscription:* As a partner admin, you can view and update your Flex Subscription and tenant subscriptions from *SUBSCRIPTIONS* > *Keystone Subscriptions* and *SUBSCRIPTIONS* > *Tenant Subscriptions* respectively. As a tenant administrator, you can only view your tenant subscriptions.
* *Users:* Based on your role, you can assign privileges to a new or existing user within a tenancy as per the requirement. The role can be NetApp administrator, NetApp administrator with read only privileges, partner administrator, or tenant administrator. As a partner administrator, you can assign only partner administrator or tenant administrator roles to new users. A tenant administrator user can assign only the tenant administrator role to other users.
* *Networks menu:* As a partner administrator, you can view the networks defined for your tenancy. You can also create subnets for your subtenant and zone from *NETWORKS* > *Subnets*. This is required while provisioning storage by the end customers or subtenants.
* API support: The `/tenants/{tenant_id}/zones/{zone_name}/subnets` and `/tenants/{tenant_id}/zones/{zone_name}/subnets/{id}/tags` APIs are being offered as a part of this release to create and view subnets for subtenants.

For more information on this feature, see the following links:

* link:nkfsosm_overview.html[Operational model, roles, and responsibilities]
* link:nkfsosm_tenancy_overview.html[Tenancy and multi-tenancy in Flex Subscription]
* link:sewebiug_dashboard.html[View Flex Subscription Dashboard]
* link:sewebiug_working_with_reports.html[View reports]
* link:sewebiug_managing_subscriptions.html[Managing subscriptions]
* link:sewebiug_managing_tenants_and_subtenants.html[Managing tenants and subtenants]
* link:sewebiug_define_network_configurations.html[Define networks for tenants and subtenants]

=== Tiering

NetApp Keystone Flex Subscription service now includes a tiering capability that leverages the NetApp FabricPool technology. It identifies less frequently used data and tiers it to a cold storage that is owned, deployed, and managed on-premises by NetApp. You can opt for tiering by subscribing to the extreme-tiering or premium-tiering performance levels.

The following APIs have been modified  to include new attribute values for the new tiering service levels:

* File services APIs
* Block store APIs

For more information, see the following links:

* link:nkfsosm_tiering.html[Tiering]
* link:nkfsosm_performance.html[Performance Service Levels]

===============================================================================
===============================================================================



== Features introduced in NetApp Service Engine 2.0.1

=== Support extended to Cloud Volumes Services for Google Cloud Platform

NetApp Service Engine now has the ability to support Cloud Volumes Services for Google Cloud Platform (GCP) in addition to its existing support for Azure NetApp Files. You can now manage subscribed services, and provision and modify Google Cloud Volumes from NetApp Service Engine.

[NOTE]
Subscriptions to Cloud Volumes Services are managed outside of NetApp Service Engine. The relevant credentials are provided to NetApp Service Engine to allow connection to the cloud services.

=== Ability to manage objects provisioned outside of NetApp Service Engine

The volumes (disks and file shares) that already exist in the customer environment and belong to the storage VMs configured in NetApp Service Engine, can now be viewed and managed as a part of your NetApp Keystone Flex Subscription (Flex Subscription). The volumes provisioned outside of the NetApp Service Engine are now listed on the *Shares* and *Disks* pages with appropriate status codes. A background process runs at a periodic interval and imports the foreign workloads within your NetApp Service Engine instance.

The imported disks and file shares may not be in the same standard as the existing disks and file shares on NetApp Service Engine. After import, these disks and file shares are categorized with `Non-Standard` status. You can raise a service request from *Support > Service Request > New Service Request* for them to be standardized and managed through the NetApp Service Engine portal.

=== SnapCenter integration with NetApp Service Engine

As a part of SnapCenter integration with NetApp Service Engine, you can now clone your disks and file shares from the Snapshots created in your SnapCenter environment, outside of your NetApp Service Engine instance. While cloning a file share or disk from an existing Snapshot on the NetApp Service Engine portal, these Snapshots are listed for your selection. An acquisition process runs in the background at a periodic interval to import the Snapshots within your NetApp Service Engine instance.

=== New screen for maintaining backups

The new *Backup* screen enables you to view and manage the backups of the disks and file shares created in your environment. You can edit the backup policies, break the backup relationship with the source volume, and also delete the backup volume with all its recovery points. This feature allows the backups to be retained (as orphan backups) even when the source volumes are deleted, for later restoration. For restoring a file share or disk from a specific recovery point, you can raise a service request from *Support > Service Request > New Service Request*.

=== Provision for restricting user access on CIFS shares

You can now specify the Access Control List (ACL) for restricting user access on a CIFS (SMB) or multi-protocol share. You can specify Windows users or groups based on the Active Directory (AD) settings to add to the ACL.
link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html#steps[Learn more].

===============================================================================
===============================================================================


== Features introduced in NetApp Service Engine 2.0

=== MetroCluster support
NetApp Service Engine supports sites configured with MetroCluster configurations. MetroCluster is a data protection feature of ONTAP that provides recovery point objectives (RPO) 0 or recovery time objectives (RTO) 0 using synchronous mirror for continuously available storage.
MetroCluster support translates to a synchronous disaster recovery feature within NetApp Service Engine. Each side of an MetroCluster instance is registered as a separate zone, each with its own subscription that includes a Data Protection Advanced rate plan.
Shares or disks created in a MetroCluster-enabled zone synchronously replicate to the second zone. The consumption of the replicated zone follows the Data Protection Advanced rate plan applicable to the zone where storage is provisioned.

=== Cloud Volumes Services support
NetApp Service Engine now has the ability to support Cloud Volumes Services. It can now support Azure NetApp Files.

[NOTE]

Subscriptions to Cloud Volumes Services are managed outside of NetApp Service Engine. The relevant credentials are provided to NetApp Service Engine to allow connection to the cloud services.

NetApp Service Engine supports:

*	Provisioning or modifying the Cloud Volumes Services volumes (including the ability to take snapshots)
*	Backing up data to a Cloud Volumes Services zone
*	Viewing Cloud Volumes Services volumes in NSE inventory
*	Viewing Cloud Volumes Services usage.

=== Host groups
NetApp Service Engine supports the use of host groups. A host group is a group of FC protocol host worldwide port names (WWPNs) or iSCSI host node names (IQNs). You can define host groups and map them to disks to control which initiators have access to the disks.
Host groups replace the need to specify individual initiators for every disk and allow for the following:

*	An additional disk to be presented to the same set of initiators
*	Updating the set of initiators across multiple disks

=== Burst usage and notifications
Some NetApp Service Engine-supported storage subscriptions allow customers to use a burst capacity over their committed capacity, which is charged separately over and above the subscribed committed capacity. It is important for users to understand when they are about to use or have used burst capacity to control their usage and costs.

==== Notification when a proposed change results in using burst capacity
A notification to display a change in the proposed provisioning that will cause a subscription to go into burst. The user can choose to continue, knowing that will put the subscription into burst or choose not to continue with the action.
link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications[Learn more].

==== Notification when subscription is in burst

A notification banner is displayed when a subscription is in burst.
link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications[Learn more].

==== Capacity report shows burst usage

Capacity report showing the number of days the subscription has been in burst and the quantity of burst capacity used.
link:sewebiug_working_with_reports.html#capacity-usage[Learn more].

=== Performance Report

A new Performance Report in the NetApp Service Engine web interface displays information about the performance of individual disks or shares on the following performance measures:

*	IOPS/TiB (Input/Output operations per second per tebibyte): The rate at which input and output operations per second (IOPS) occur on the storage device.
*	Throughput in MBps: The data transfer rate to and from the storage media in megabytes per second.
*	Latency (ms): The average time for reads and writes from the disk or share in milliseconds.

=== Subscription management

Subscription management has been enhanced. You can now:

* Request a data protection add-on, or request additional capacity for a data protection add-on for a subscription or service
*	View data protection usage capacity

=== Billing enhancement

Billing now supports the ability to measure and bill for snapshot usage for ONTAP (file and block) storage.

=== Hidden CIFS shares

NetApp Service Engine supports creating hidden CIFS shares.
