---
sidebar: sidebar
permalink: rn_whats_new.html
keywords: netapp, keystone, release notes, new features, what's new,
summary: new features in NetApp Service Engine
---

= What's new in NetApp Service Engine
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-05
//

[.lead]
The following features and enhancements have been introduced in NetApp Service Engine 2.0.1:

= Features introduced in Keystone 2.0.1

===  Support extended to Cloud Volumes Services for Google Cloud Platform

NetApp Service Engine now has the ability to support Cloud Volumes Services for Google Cloud Platform (GCP) in addition to its existing support for Azure NetApp Files. You can now manage subscribed services and provision and modify Google Cloud Volumes from NetApp Service Engine.

[NOTE]
Subscriptions to Cloud Volumes Services are managed outside of NetApp Service Engine. The relevant credentials are provided to NetApp Service Engine to allow connection to the cloud services.

=== Ability to manage objects provisioned outside of NetApp Service Engine

The volumes (disks and file shares) that already exist in the customer environment and belong to the storage VMs configured in NetApp Service Engine, can now be viewed and managed as a part of your Keystone subscription. The volumes provisioned outside of the NetApp Service Engine are now listed on the *Shares* and *Disks* pages with appropriate status codes. A background process runs at a periodic interval and imports the foreign workloads within your NetApp Service Engine instance.

The imported disks and file shares may not be in the same standard as the existing disks and file shares on NetApp Service Engine. After import, these disks and file shares are categorized with `Non-Standard` status. You can raise a service request from *Support > Service Request > New Service Request* for them to be standardized and managed through the NetApp Service Engine portal.

=== SnapCenter integration with NetApp Service Engine

As a part of SnapCenter integration with NetApp Service Engine, you can now clone your disks and file shares from the Snapshots created in your SnapCenter environment, outside of your NetApp Service Engine instance. While cloning a file share or disk from an existing Snapshot on the NetApp Service Engine portal, these Snapshots are listed for selection on the *Create Disk from Snapshot* pop-up. An acquisition process runs in the background at a periodic interval to import the Snapshots within your NetApp Service Engine instance.

=== New screen for maintaining backups

The new *Backup* screen enables you to view and manage the backups of the disks and file shares created in your environment. You can edit the backup policies, break the backup relationship with the source volume, and also delete the backup volume with all its recovery points. This feature allows the backup to be retained (as an orphan backup) even when the source volume is deleted, for later restoration. For restoring a file share or disk from a specific recovery point, you can raise a service request from *Support > Service Request > New Service Request*.

=== Provision for restricting user access on CIFS (SMB) shares

You can now specify the Access Control List (ACL) for restricting user access on a CIFS (SMB) or multi-protocol shares. You can specify Windows users or groups based on the Active Directory (AD) to add to the ACL.
link:https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html#steps[Learn more].

= Features introduced in Keystone 2.0

=== MetroCluster support
NetApp Service Engine supports sites configured with MetroCluster configurations. MetroCluster is a data protection feature of ONTAP that provides recovery point objectives (RPO) 0 or recovery time objectives (RTO) 0 using synchronous mirror for continuously available storage.
MetroCluster support translates to a synchronous disaster recovery feature within NetApp Service Engine. Each side of an MetroCluster instance is registered as a separate zone, each with its own subscription that includes a Data Protection Advanced rate plan.
Shares or disks created in a MetroCluster-enabled zone synchronously replicate to the second zone. The consumption of the replicated zone follows the Data Protection Advanced rate plan applicable to the zone where storage is provisioned.

=== Cloud Volumes Services support
NetApp Service Engine now has the ability to support Cloud Volumes Services. It can now support Azure NetApp Files.

[NOTE]

Subscriptions to Cloud Volumes Services are managed outside of NetApp Service Engine. The relevant credentials are provided to NetApp Service Engine to allow connection to the cloud services.

NetApp Service Engine supports:

*	Provisioning or modifying the Cloud Volumes Services volumes (including the ability to take snapshots)
*	Backing up data to a Cloud Volumes Services zone
*	Viewing Cloud Volumes Services volumes in NSE inventory
*	Viewing Cloud Volumes Services usage.

=== Host groups
NetApp Service Engine supports the use of host groups. A host group is a group of FC protocol host worldwide port names (WWPNs) or iSCSI host node names (IQNs). You can define host groups and map them to disks to control which initiators have access to the disks.
Host groups replace the need to specify individual initiators for every disk and allow for the following:

*	An additional disk to be presented to the same set of initiators
*	Updating the set of initiators across multiple disks

=== Burst usage and notifications
Some NetApp Service Engine-supported storage subscriptions allow customers to use a burst capacity over their committed capacity, which is charged separately over and above the subscribed committed capacity. It is important for users to understand when they are about to use or have used burst capacity to control their usage and costs.

==== Notification when a proposed change results in using burst capacity
A notification to display a change in the proposed provisioning that will cause a subscription to go into burst. The user can choose to continue, knowing that will put the subscription into burst or choose not to continue with the action.
link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications[Learn more].

==== Notification when subscription is in burst

A notification banner is displayed when a subscription is in burst.
link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#burst-usage-notifications[Learn more].

==== Capacity report shows burst usage

Capacity report showing the number of days the subscription has been in burst and the quantity of burst capacity used.
link:sewebiug_working_with_reports.html#capacity-usage[Learn more]

=== Performance Report

A new Performance Report in the NetApp Service Engine web interface displays information about the performance of individual disks or shares on the following performance measures:

*	IOPS/TiB (Input/Output operations per second per tebibyte): The rate at which input and output operations per second (IOPS) occur on the storage device.
*	Throughput in MBps: The data transfer rate to and from the storage media in megabytes per second.
*	Latency (ms): The average time for reads and writes from the disk or share in milliseconds.

=== Subscription management

Subscription management has been enhanced. You can now:

* Request a data protection add-on, or request additional capacity for a data protection add-on for a subscription or service
*	View data protection usage capacity

=== Billing enhancement

Billing now supports the ability to measure and bill for snapshot usage for ONTAP (file and block) storage.

=== Hidden CIFS shares

NetApp Service Engine supports creating hidden CIFS shares.
