---
sidebar: sidebar
permalink: seapiref_@consumer@_administration_apis.html
keywords:
summary:
---

= (Consumer) Administration APIs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-19 09:25:10.014016
//

[.lead]
The (consumer) administration APIs consist of methods that allow you to perform the following tasks:

* Sign in, set a password, and refresh an authentication token.
* Retrieve jobs and view job details.
+
See link:seapiref_jobs.html.html#retrieve-jobs>[Retrieve jobs] and link:seapiref_jobs.html.html#retrieve-a-job-by-job-id>[Retrieve a job-by-job ID].

* Retrieve regions.
+
See link:seapiref_regions.html#retrieve-regions>[Retrieve regions] and link:seapiref_regions.html#retrieve-a-region-by-name>[Retrieve a region by name].

* Retrieve service levels.
+
See link:seapiref_service_levels.html#retrieve-service-levels>[Retrieve Service Levels] and link:seapiref_service_levels.html#retrieve-service-levels-by-name>[Retrieve Service Levels by Name].

* Work with subtenants.
+
See:

** link:seapiref_subtenants.html#retrieve-all-subtenants>[Retrieve all subtenants]
** link:seapiref_subtenants.html#retrieve-a-subtenant-by-id>[Retrieve a subtenant by ID]
** link:seapiref_subtenants.html#modify-a-subtenant-by-id>[Modify a subtenant]
** link:seapiref_subtenants.html#delete-a-subtenant-by-id>[Delete a subtenant by ID]
* Work with subtenants.
+
See:

** link:seapiref_tenants.html#retrieve-all-tenants>[Retrieve all tenants]
** link:seapiref_tenants.html#retrieve-a-tenant-by-id>[Retrieve a tenant by ID]
** link:seapiref_tenants.html#create-a-tenant>[Create a tenant]
** link:seapiref_tenants.html#modify-the-tenant>[Modify the tenant]
** link:seapiref_tenants.html#delete-the-tenant>[Delete the tenant]
* Retrieve users.
+
link:seapiref_users.html#retrieve-all-users>[Retrieve all users], link:seapiref_users.html#retrieve-a-user-by-id>[Retrieve a user by ID], and link:seapiref_users.html#retrieve-a-user-by-user-name>[Retrieve a user by user name].

* Retrieve zones.
+
See link:seapiref_zones.html#retrieve-all-zones>[Retrieve all zones] and link:seapiref_zones.html#retrieve-a-zone-by-name>[Retrieve a zone by name]

The following table lists the consumer APIs documented in this section.

|===
|HTTP Method |Path |Description

|`POST`
|`/v2.1/auth/password`
|Set the password for a user.
|`POST`
|`/v2.1/auth/password`
|Refresh authentication JWT.
|`POST`
|`/v2.1/auth/signin`
|Sign in.
|`GET`
|`/v2.1/auth/regions`
|Retrieve regions.
|`GET`
|`/v2.1/auth/regions/{name}`
|Retrieve regions by name.
|`GET`
|`/v2.1/auth/zones`
|Retrieve zones.
|`GET`
|`/v2.1/auth/zones/{name}`
|Retrieve zones by name.
|`GET`
|`/v2.1/jobs/`
|Retrieve jobs.
|`GET`
|`/v2.1/jobs/{id}`
|Retrieve jobs by ID.
|===

=== Reset user password

Use the method listed in the following table reset the user password.

|===
|HTTP Method |Path |Description |Parameters

|`POST`
|`/v2.1/auth/password`
|Reset the password.
|None
|===

Required request body attributes: `username` (string), `new_password` (string)

*Request body example:*

....
{
  "username": "MyName",
  "old_password": "oldPassword",
  "new_password": "newPassword"
}
....

*Response body example:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "user": {
          "id": "5e61aa814559c20001df1a5f",
          "username": "MyName",
          "firstName": "MyFirstName",
          "lastName": "MySurname",
          "displayName": "CallMeMYF",
          "email": "user@example.com",
          "tenancies": [
            {
              "id": "5e5f1c4f253c820001877839",
              "name": "MyTenant",
              "code": "testtenantmh",
              "role": "user"
            }
          ]
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik15TmFtZSIsImV4cCI6MTU4MzgxNjg3MX0.ZuRXjDPVtc2pH-e9wqgmszVKCBYS2PLqux2YwQ5uoAM"
      }
    ]
  }
}
....

=== Refresh authentication token

Use the method listed in the following table to refresh the authentication token.

|===
|HTTP Method |Path |Description |Parameters

|`POST`
|`/v2.1/auth/refresh`
|Refresh the authentication token.
|None
|===

Required request body attributes: `none`

*Request body example:*
....
none
....

*Response body example:*
....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "user": {
          "id": "5d914547869caefed0f3a00c",
          "username": "myusername",
          "firstName": "myfirstname",
          "lastName": "",
          "displayName": "Myfirstname Mysurname",
          "email": "",
          "tenancies": [
            {
              "id": "5d914499869caefed0f39eee",
              "name": "MyOrg",
              "code": "myorg",
              "role": "admin"
            },
            {
              "id": "5d9417aa869caefed0f7b4f9",
              "name": "ABCsafe",
              "code": "abcsafe",
              "role": "admin"
            }
          ]
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVsbGlvdCIsImV4cCI6MTU4MzgxNzA2N30.FdKD3QhPoNdWdbMfZ0bzCMTHluIt6HNP311F482K9AY"
      }
    ]
  }
}
....

=== Sign in

Use the method listed in the following table to sign in.

|===
|HTTP Method |Path |Description |Parameters

|`POST`
|`/v2.1/auth/signin`
|Log in as a user.
|None
|===

Required request body attributes: `username` (string), `new_password` (string)

*Request body example:*
....
{
  "username": "MyName",
  "password": "newPassword"
}
....

*Response body example:*

....
{
  "status": {
    "user_message": "Authentication succeeeded.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "user": {
          "id": "5e61aa814559c20001df1a5f",
          "username": "MyName",
          "firstName": "MyFirstName",
          "lastName": "MySurname",
          "displayName": "CallMeMYF",
          "email": "user@example.com",
          "tenancies": [
            {
              "id": "5e5f1c4f253c820001877839",
              "name": "MyTenant",
              "code": "testtenantmh",
              "role": "user"
            }
          ]
        },
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik15TmFtZSIsImV4cCI6MTU4MzgxNzQwMH0._u_UyYrzg_RewF-9ClIGoKQhfZYWrixZYBrsj1kh1hI"
      }
    ]
  }
}
....
