---
sidebar: sidebar
permalink: seapiref_reporting_apis.html
keywords:
summary:
---

= Reporting APIs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-19 09:25:09.992577
//

[.lead]
Use the methods in the following table to retrieve and generate reports.

|===
|HTTP Method |Path |Description

|`GET`
|`/v2.1/reports`
|Retrieve all list of reports.
|`POST`
|`/v2.1/reports/{filename}`
|Retrieve a report.
|===

=== Retrieve a list of reports

Use the method listed in the following table to retrieve a list of reports.

|===
|HTTP Method |Path |Description |Parameters

|`GET`
|`/v2.1/reports`
|Retrieve all available reports for a tenant.
Reports can be filtered by date range.
a|* `tenant_id (string)`
* `start(string)`: Retrieve reports more recent that the date specified in start.
* `end (string)`: Retrieve reports older that the date specified in end.
|===

Required request body attributes: `none`

*Request body example:*

....
none
....

*Response body example:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "filename": "string"
      }
    ]
  }
}
....

==== Retrieve a report identified by file name

Use the method in the following table to retrieve a report identified by the file name.

|===
|HTTP Method |Path |Description |Parameters

|`GET`
|`/v2.1/reports/{filename}`
|Retrieve a report identified by the file name.
|`filename (string)`: The report file name.
|===

Required request body attributes: `none`

*Request body example:*

....
none
....

*Response body example:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "filename": "string"
      }
    ]
  }
}
....
