---
sidebar: sidebar
permalink: seapiref_block_storage_apis.html
keywords: netapp, keystone, block storage, block stores, disks, host groups, initiators, apis
summary: Keystone block storage APIs
---

= Block storage APIs
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can use Block Storage APIs to view and manage your block storage.

Before you create disks, you have to create block stores. When you create a disk, you have to a create host group or select an existing host group to access the disk. For more information, see link:sewebiug_working_with_block_storage_overview.html[Work with block storage].

== Block stores

You can use Block Store APIs to retrieve and manage your block stores.

[cols="1,1,3,2",options="header"]
|===
| HTTP Verb | Path | Description | Mandatory parameters/Request body

a|`GET`
a|`/v2.1/blockstores`
|You can retrieve the details of all your block stores. Retrieves details of the block stores, such as block store ID, IP address, region, zone, subnet ID, and tags.
a|`offset`: The number of items to skip before starting to collect the result set.
`limit`: The numbers of items to return.

a|`GET`
a|`/v2.1/blockstores/{id}`
|You can retrieve the details of a specific block store. Retrieves details of the block store, such as IP address, region, zone, subnet ID, and tags based on the entered ID.
a|`id`: The ID of the block store.

a|`POST`
a|`/v2.1/blockstores`
|You can create a block store. Add the values in the request body to create a block store with the specified parameters, such as service protocol, subtenant ID, zone, subnet ID, and tags.
a|`subtenant_id`: The ID of the subtenant.
`zone`: The name of the zone.
`subnet_id`: The ID of the subnet.

a|`POST`
a|`/v2.1/blockstores/{id}/tags`
|You can create or replace tags for a block store. Add the ID of the block store, and the values for the tags in the "key:value pair" format in the request body.
a|`id`: The ID of the block store.

a|`PUT`
a|`/v2.1/blockstores/{id}`
|You can modify any block store based on its ID. Add the ID of the block store, and the values that you want to modify in the request body, such as zone, service protocol, and tags.
a|`id`: The ID of the block store.

a|`DELETE`
a|`/v2.1/blockstores/{id}`
a|You can delete any block store by its ID.
[NOTE]
====
Before you delete a block store, you should delete all the disks mapped to it.
====
a|`id`: The ID of the block store.
|===

== Disks

You can use Disks APIs to retrieve and manage your disks.

[cols="1,1,3,2",options="header"]
|===
| HTTP Verb | Path | Description | Mandatory parameters/Request body

a|`GET`
a|`/v2.1/disks`
|You can retrieve the details of all your disks. Retrieves details of the disks, such as block store ID, name, disk path, protocol, snapshot policy, and tags.
a|`offset`: The number of items to skip before starting to collect the result set.
`limit`: The numbers of items to return.

a|`GET`
a|`/v2.1/disks/{id}`
|You can retrieve the details of a specific disk. Retrieves details of the disk, such as block store ID, name, disk path, protocol, snapshot policy, and tags based on the entered ID.
a|`id`: The ID of the disk.

a|`POST`
a|`/v2.1/disks`
|You can create a disk. Add the values in the request body to create a disk with the specified parameters, such as subtenant ID, zone, name, disk path, snapshot policy, backup policy, and tags.
a|`subtenant_id`: The ID of the subtenant.
`zone`: The name of the zone.
`name`: The name of the disk.
`disk_path`: The path of the disk.
`protocol`: The storage protocol used for block device access.
`os_type`: The type of the host operating system.
`hostgroup_mappings`: The host group mappings.
`service_level`: The service level name applicable: Standard, Premium, Premium-Tiering, Extreme, or Extreme-Tiering.
`size_gb`: The size of the disk in GBs.

a|`POST`
a|`/v2.1/disks/{id}/snapshot/{name}`
|You can create a snapshot of a disk.
a|`id`: The ID of the disk.
`name`: The name of the snapshot.

a|`POST`
a|`/v2.1/disks/{id}/tags`
|You can create or replace tags for a disk. Add the ID of the disk and the values for the tags in the "key:value pair" format in the request body.
a|`id`: The ID of the disk.

a|`PUT`
a|`/v2.1/disks/{id}`
|You can modify any disk based on its ID. Add the ID of the disk, and the values that you want to modify in the request body, such as such as name, service level, snapshot policy, backup policy, and tags.
a|`id`: The ID of the disk.
`hostgroup_mappings`: The host group mappings.

a|`DELETE`
a|`/v2.1/disks/{id}`
|You can delete any disk by its ID.
a|`id`: The ID of the disk.

a|`DELETE`
a|`/v2.1/disks/{id}/snapshot/{name}`
|You can delete any snapshot of a disk by the ID of the disk and the name of the snapshot.
a|`id`: The ID of the disk.
`name`: The name of the snapshot.
|===

== Host groups

Access control to disks is managed with host groups. You can retrieve and manage host groups using Host Groups APIs.

[cols="1,1,3,2",options="header"]
|===
| HTTP Verb | Path | Description | Mandatory parameters/Request body

a|`GET`
a|`/v2.1/hostgroups`
|You can retrieve the details of all your host groups. Retrieves details of the host groups, such as name, subtenant details, tenant details, zone, protocol, initiators, disks using the host group, and tags.
a|`offset`: The number of items to skip before starting to collect the result set.
`limit`: The numbers of items to return.

a|`GET`
a|`/v2.1/hostgroups/{id}`
|You can retrieve the details of a specific host group. Retrieves details of the host group, such as name, subtenant details, tenant details, zone, protocol, initiators, disks using the host groups, and tags based on the entered ID.
a|`id`: The ID of the host group.

a|`POST`
a|`/v2.1/hostgroups`
|You can create a host group. Add the values in the request body to create a host group with the specified parameters, such as name, subtenant ID, zone, protocol, initiators, and tags.
a|`name`: The name of the host group.
`subtenant_id`: The ID of the subtenant.
`zone`: The name of the zone.
`protocol`: The storage protocol used for block device access.
`os_type`: The type of the host operating system.

a|`POST`
a|`/v2.1/hostgroups/{id}/tags`
|You can create or replace tags for a host group. Add the ID of the host group and the values for the tags in the "key:value pair" format in the request body.
a|`id`: The ID of the host group.

a|`DELETE`
a|`/v2.1/hostgroups/{id}`
|You can delete any host group by its ID.
a|`id`: The ID of the host group.
|===

== Initiators in a host group

You can use Host Groups APIs to retrieve and manage the initiators mapped to your host groups.

[cols="1,1,3,2",options="header"]
|===
| HTTP Verb | Path | Description | Mandatory parameters/Request body

a|`GET`
a|`/v2.1/hostgroups/{id}/initiators`
|You can retrieve the details of all your initiators. Retrieves initiators and their aliases.
a|`id`: The ID of the host group.

a|`GET`
a|`/v2.1/hostgroups/{id}/initiators/{alias}`
|You can retrieve the details of a specific initiator. Retrieves the initiator based on the entered ID and alias.
a|`id`: The ID of the host group.
`alias`: The alias name of the initiator.

a|`POST`
a|`/v2.1/hostgroups/{id}/initiators`
a|You can create an initiator for a host group. Add the values for the initiator and its alias in the request body to create an initiator for the host group.
[NOTE]
====
When adding initiators to a host group, the initiator should match the host group protocol: use IQNs for host groups with iSCSI protocol, and WWPNs for host groups with FC protocol.
====
a|`id`: The ID of the host group.
`alias`: The alias name of the initiator.
`initiator`: The initiator (iSCSI Qualified Names or FC WWPNs).

a|`PATCH`
a|`/v2.1/hostgroups/{id}/initiators/{alias}`
|You can modify an initiator. Add the new initiator in the request body.
a|`id`: The ID of the host group.
`alias`: The alias name of the initiator.
`initiator`: The initiator (iSCSI Qualified Names or FC WWPNs).`

a|`DELETE`
a|`/v2.1/hostgroups/{id}/initiators/{alias}`
a|You can delete an initiator by the ID of the host group and the alias of the initiator.
[NOTE]
====
Deleting an initiator from a host group affects all the disks to which the host group is mapped to.
====
a|`id`: The ID of the host group.
`alias`: The alias name of the initiator.
|===
