---
sidebar: sidebar
permalink: seapiref_service_requests.html
keywords: netapp, keystone, service, requests,
summary: Keystone service requests
---

= Service requests
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Use the methods listed in the following table to create and retrieve service requests.


|===
|HTTP Method |Path |Description
|`GET`
|`/v2.1/tenants/{tenant_id}/servicerequests`
|Retrieve service requests.
|`GET`
|`/v2.1/tenants/{tenant_id}/servicerequests/{id}`
|Retrieve a service request by ID.
|`POST`
|`/v2.1/tenants/{tenant_id}/servicerequests/`
|Create a service request.
|`GET`
|`/v2.1/tenants/{tenant_id}/servicerequests/categories`
|Retrieve service request categories.
|===

== Service request attributes

The following table lists the service request attributes.

|===
|Attribute |Type |Description
|`Id`
|String
|An identifier for the service request. For example: `SRQ0035952014.`
|`subject`
|String
|The subject of the service request.
|`comment`
|String
|A comment on the service request
|`category`
|String
|The category of the request: Backup, disaster recovery, technical, other, or subscription.
|`priority`
|String
|The priority of the service request: very low, low, normal, high, or urgent.
|`subscription`
|String
|The Zuora subscription number.
|`commitment`
|–
a|Subscription commitment details, including:

* Service level (string): Service level: Standard, Premium, or Extreme.
* New_commitment (integer): New total capacity required.
|`zone`
|String
|The zone name.
|`subtenant_id`
|String
|The subtenant identifier.
|`storage_object_type`
|String
|Storage object type: File server or block store.
|`storage_object_id`
|String
|The identifier of the storage object.
For example:
`5d2fb0fb4f47df00015274e3`
|`service_type`
|String
|The service type: File services, block storage, or object storage.
|===

== Retrieve service requests

Use the method listed in the following table to retrieve service request categories for the specified tenant.

|===
|HTTP Method |Path |Description |Parameters
|`GET``
|`/v2.1/tenants/{tenant_id}/servicerequests`
|Retrieve service requests.
|`tenant_id`: (Optional) Return the service requests for the specified tenant.

`offset` and `limit`– see link:seapiref_netapp_service_engine_rest_apis.html#pagination>[Common Pagination]
|===

Required request body attributes: `none`

*Request body example:*

....
none
....

*Response body example:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 34,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 6,
    "limit": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....

== Retrieve a service request by ID

Use the method listed in the following table to retrieve a service request by service request ID.

|===
|HTTP Method |Path |Description |Parameters
|`GET`
|`/v2.1/tenants/{tenant_id}/servicerequests/{id}`
|Retrieve a service request by ID.
a|* `tenant_id`: Tenant ID
* `id`: Service request IDFor example: SRQ0035952014
|===
Required request body attributes: `none`

*Request body example:*

....
none
....

*Response body example:*
....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== Create a service request

Use the method listed in the following table to create a service request.

|===
|HTTP Method |Path |Description |Parameters
|`POST`
|`/v2.1/tenants/{tenant_id}/servicerequests/categories`
|Create a service request.
|`tenant_id`: The tenant identifier.
|===

Required request body attributes: the required attributes are dependent on the category of service request. The following table lists the request body attributes.

|===
|Category |Required
|Subscription
|`subscription` and `commitment`
|Disaster recovery
|`storage_object_type`, `subtenant_id`, and `storage_object_id`
|Technical
|`subtenant_id` and `service_type`
If `service_type` is file services or block storage, zone is required.
|Other
|Zone
|===

*Request body example:*
....
{
  "subject": "string",
  "comment": "string",
  "category": "subscription",
  "priority": "Normal",
  "subscription": "A-S00003969",
  "commitment": {
    "service_level": "standard",
    "new_commitment": 10
  },
  "zone": "au-east1-a",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "storage_object_type": "fileserver",
  "storage_object_id": "5d2fb0fb4f47df00015274e3",
  "service_type": "File Services"
}
....

*Response body example:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "string",
        "subject": "string",
        "description": "string",
        "status": "New",
        "priority": "Normal",
        "createdDate": "2020-05-12T03:18:25+0000",
        "UpdatedDate": "2020-05-12T03:18:25+0000"
      }
    ]
  }
....

== Retrieve service request categories

The following table lists the retrieve service request categories for a specified tenant.

|===
|HTTP Method |Path |Description |Parameters
|`GET`
|`/v2.1/tenants/{tenant_id}/servicerequests/categories`
|Retrieve service requests categories.
|`tenant_id:` (Optional) Return the service requests for a specified tenant.

|===

Required request body attributes: `none`

*Request body example:*

....
none
....

*Response body example:*

....
{
  "status": {
    "user_message": "Okay. Returned 5 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 5,
    "records": [
      {
        "key": "dr",
        "value": "Disaster Recovery Failover"
      },
      {
        "key": "technical",
        "value": "Technical Issue"
      },
      {
        "key": "other",
        "value": "Other"
      },
      {
        "key": "subscription",
        "value": "Subscription Management"
      },
      {
        "key": "backup",
        "value": "Backup Restore"
      }
    ]
  }
}
....
