---
sidebar: sidebar
permalink: sewebiug_create_an_s3_key_for_a_user.html
keywords: netapp, keystone, create, S3, key, user,
summary: Keystone create an S3 key for a user
---

= Create an S3 key for a user
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Use this method to create an S3 key for a user.

Make sure that you capture the key immediately after it is created. There is no way to retrieve key details after it has been created.

.Steps

. View the object storage user link:sewebiug_view_the_object_storage_group_and_users.html[View object storage group and users].
. Make sure the correct subtenant is selected and you have clicked the *Users* tab.
. Locate the user in the list and click the key icon for that group.
+
For details about working with items in lists, see link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions[List view actions].

. The *Manage S3 Keys* dialog box displays showing the list of keys for the user. For information about keys, see https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#specify-permissions-in-a-policy[Specify permissions in a policy].
. If there are no existing keys for the user, click *Create S3 Key* to view the fields to create a key.
. If you want the key to expire, specify the expiry date and expiry time in UTC. Otherwise, leave the default values in these fields.
. To create the key, click the checkmark. The *S3 Key Details* dialog box is displayed showing the access key and the secret key.
. Copy both the access and secret keys in preparation for advising the user of the details.
+
Make sure that you capture the key details before closing the *S3 Key Details* dialog box. After closed, the key details will be obscured and you will not be able to retrieve them.

. Click *Close*.
. Click *Close* again to close the Manage S3 Keys dialog.
