---
sidebar: sidebar
permalink: sewebiug_modify_an_object_storage_user.html
keywords: netapp, keystone, modify, object, storage, user,
summary: Keystone modify an object storage user
---

= Modify an object storage user
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Use this method to modify details of an object storage user such as the user name and the group to which they are assigned.

.Steps

. View the object storage user link:sewebiug_view_the_object_storage_group_and_users.html[View object storage group and users].
. Make sure the correct subtenant is selected and you have clicked the *Users* tab.
. Locate the user in the list and click the edit icon for that user.
+
For details about working with items in lists, see link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions[List view actions].

. In the *Edit User* dialog box, change the object storage group for the user.
. Click *Update*. This creates a job to update the group for the user. For information about tracking jobs, see link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator[here].
