---
sidebar: sidebar
permalink: sewebiug_working_with_block_storage_overview.html
keywords:
summary:
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:39.393104
//

[.lead]
In block storage systems, the data storage is broken up into individual pieces each with a unique identifier. NetApp Service Engine refers to the block data storage as a block store, and the individual pieces as disks.

Block stores belong to a subtenant and are specified within a zone (one block store per zone per subtenant). A block store has networking attributes (for example,  IP address and VLAN ID) which are used to access disks through the iSCSI or FC protocol. Disaster recovery DP can be enabled on a block store. For more information, see Disaster Recovery <xref>.

Block stores must be initialized before they can be used. Where block storage is available and it has not been initialized, it can be initialized prior to creating the first disk on the block store as part of the Create Disk process.

Disks are created on block stores. Disks have many configurable attributes included capacity and associated service level. DP options such as Snapshots <xref> and Disaster Recovery <xref> can be enabled for a disk.

Access to disks is controlled through host groups. Host groups consist of initiator node names; by mapping one or more host groups to a disk, you can define which initiators have access to the disk.

Host groups:

* Are protocol specific. They can be either:
** FC protocol host groups: these consist of initiators that are FC World Wide Port Names (WWPNs). For example,  `20:56:00:a0:98:5c:0d:da`).
** iSCSI protocol host groups: these consist of initiators that are iSCSI qualified names (IQNs). For example, `iqn.1998-01.com.vmware:esx2`.
* Consist of alias/initiator pairs. An alias allows a simple way to identify the initiator. For example, `esxserver1`.
* Can be created without any initiators. Empty host groups can be mapped to disks as placeholders but must be fully defined to allow access to the disk. Using host groups allows for:

* Mapping multiple disks to the same set of initiators
* Updating the set of initiators across multiple disksThis section contains information on: 

* Working with host groups:
** View host groups
** Create a host group
** Modify host group initiators
** Delete a host group
* Working with disks:
** View disks
** Create a new disk
** Create a disk from snapshot
** Modify a disk
** Delete a disk
** Create an adhoc snapshot of a disk


