---
sidebar: sidebar
permalink: sewebiug_dashboard.html
keywords: netapp, keystone, view, dashboard, capacity utilization, monthly charges, alerts, service request
summary: Dashboard view
---

= View Flex Subscription Dashboard
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The Dashboard provides a quick overview of your NetApp Keystone storage subscriptions. It displays information about the capacity used, billing against your usage, and recent alerts and service requests.

The Dashboard displays important information across the following widgets, which can be clicked through for in-depth analysis:

* *Capacity Utilization:* Displays your capacity utilization for Keystone Flex Subscription, Keystone Flex Utility, and Cloud Services. You can view the committed and consumed capacities, as well as the capacity in burst and identify if you need to add more capacity to your subscriptions. For more information on capacity utilization, see link:sewebiug_working_with_reports.html[View reports].
* *Monthly Charges:* Displays the aggregated monthly charges for the last three months and projected charges for the current month, based on usage trends. You can select any month to view the monthly subscription-level billing.
* *Alerts:* Displays the summary of the most recent alerts, such as the status, message, and when it was created. For more informationon alerts, see link:sewebiug_alerts.html[Create and manage alerts].
* *Service Requests:* Displays the summary of the most recent service requests, sorted by priority and when they were created. For more information on service requests, see link:sewebiug_raise_a_service_request.html[Raise a service request].
