---
sidebar: sidebar
permalink: sewebiug_modify_an_object_storage_user.html
keywords:
summary:
---

= Modify an object storage user
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:39.819183
//

[.lead]
Use this method to modify details of an object storage user such as the user name and the group to which they are assigned.

=== Steps

. Display the link:sewebiug_view_a_list_of_users.html#view-a-list-of-users[Users List].
. Make sure the correct subtenant is selected and the display is showing Users (not Groups).
. Locate the user in the list and click the Edit icon for that group.
+
For details about working with items in lists, see link:sewebiug_netapp_service_engine_web_interface_overview#list-view[List view actions].

. In the Edit User dialog box:
.. Enter the user name.
.. Select the object storage group to which the user belongs.
. Click Update. This creates a job to create the user with the specified settings.
