---
sidebar: sidebar
permalink: sewebiug_managing_azure_volumes.html
keywords: netapp, keystone, managing, azure, volumes,
summary: Keystone managing Azure volumes
---

= Managing Azure volumes
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This section describes how to manage Azure volumes.

[NOTE]
Managing Azure Volumes requires Customer Admin access.

This section describes how to perform the following tasks:

* View a list of Azure volumes.
* Add an Azure volume.
* Modify Azure volume details.
* Delete an Azure volume.

== View a list of Azure volumes

The Azure Volumes list displays a list of Azure volumes pools for a specified subtenant and location. To view the list, select *FILE SERVICES > Azure Volumes* from the menu.

The list displays simple information about each Azure volume. The action icons next to each Azure volume allow you to modify or delete the Azure volume.

== Add an Azure volume

This section describes how to add an Azure volume.

.Before you begin

You will need:

* The subtenant to which the Azure volume belongs
*	The ANF Account
*	Azure Virtual Network (VNet) and Subnet
*	The capacity pool to house the volume
*	A name for the volume
*	The file path
*	The quota (size) of the volume


.Steps

. Select *FILE SERVICES > Azure Volumes* from the menu.
. Click *Create*.
. In the Create Azure Volume dialog box, specify the subtenant, the ANF account, the VNet, the subnet, the capacity pool, the name of the volume, the file path and the quota. Ensure that you enter a unique file path for a successful volume creation.
. If required, add tags to the volume.
. Click *Create*. When an Azure volume is created, the state of the volume changes to `Succeeded` (can be viewed in the Azure Volumes list).

== Modify Azure volume details

Use this method to modify an Azure Volume’s details. You can modify the file path and quota, and add or remove tags.

.Steps

. Select *FILE SERVICES > Azure Volumes* from the menu.
. From the list, locate the Azure volume and click the edit icon.
. In the Manage Azure Volume dialog box, make the required changes. If you are modifying the file path or quota, ensure that the file path is unique and that the quota does not exceed the available quota in the pool.
. Click *Update*.

== Delete an Azure volume

Use this method to delete an Azure volume.

.Steps

. Select *FILE SERVICES > Azure Volumes* from the menu.
. Locate the Azure volume in the list and click the delete icon.
. In the Confirm Delete dialog box, enter the name of the Azure volume to be deleted.
. Click *Confirm*.
