---
sidebar: sidebar
permalink: sewebiug_getting_started_overview.html
keywords: netapp, keystone, getting, started, overview,
summary: Keystone getting started overview
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:39.019319
//

[.lead]
This section describes how to get started by using the NetApp Service Engine portal.

[NOTE]
When you navigate through the NetApp Service Engine portal, you can see that some of the information, such as your region and zone, is automatically populated based on your subscription setup configured by the support team.

To begin your activities on this portal:

* Log in to the NetApp Service Engine web interface.
** Log in with a user name and password
** Log in with NetApp SSO
For information, see link:sewebiug_log_in_to_the_netapp_service_engine_web_interface.html[Log in to the NetApp Service Engine web interface]
* Select tenant. The dashboard is displayed. For information, see link:sewebiug_dashboard.html[View Flex Subscription Dashboard]

For NetApp Service Engine web interface overview, see link:sewebiug_netapp_service_engine_web_interface_overview.html[NetApp Service Engine web interface overview]
