---
sidebar: sidebar
permalink: sewebiug_add_a_subscribed_service.html
keywords: netapp, keystone, add, cloud, service,
summary: Keystone add a cloud service
---

= Add a cloud service
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This section describes how to add a cloud service.

NetApp Service Engine supports Azure NetApp Files.

=== Before you begin
You need the information about the cloud services, including credentials to connect to the service. The information varies with the cloud service type.

=== Steps

. Select *Cloud Services* from the menu.
. Click *Create*.
. On the Create Cloud Service page, select the cloud service type and then complete the relevant information for that service type:
+
*Azure:*

.. Select the Subtenant.
.. Enter a name for the OCCM Working Environment that will be created for the service.
.. Enter the Azure Directory (tenant) ID, the Azure Client ID, Azure Client Secret and the Name of the cloud service.
+

. Specify tags for the service if required.
. Click *Create*.
