---
sidebar: sidebar
permalink: sewebiug_managing_tenants_and_subtenants.html
keywords: netapp, keystone, managing, subtenants,
summary: Keystone managing subtenants
---

= Managing tenants and subtenants
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can view and manage your tenants and subtenants by using NetApp Service Engine. The initial tenancy is set up by NetApp support for service providers/partners and tenants. The region, zone, and subscription are already configured by support, and are available when you create tenants and subtenants under your tenancy.

== Tenants

If you are a partner admin, you can create, modify, and delete a tenant from *ADMINISTRATION* > *Tenants*. Tenant admins can only view their respective Tenant Subscriptions and subtenants. For the tenants under your partner tenancy, you can also define the network.

=== Create a tenant

You can create a tenant if you are a partner admin. You can also create and manage networks for each tenant. For more information on creating networks, see link:sewebiug_define_network_configurations.html[Define network configurations with subnets].

.Steps

. Click *Create Tenant*.
. Add a name and the code.
The code that represents the tenant should be unique within a NetApp Service Engine instance and consist of lower-case characters.
. Click *Create*.

NOTE: You can only modify the name and description of an existing tenant. Additionally, you cannot delete a tenant that has subtenants or storage components associated with it.

== Subtenants

If you are a Partner admin or a Tenant admin, you can view and manage subtenants.

=== Create a subtenant

If you are a Partner admin or a Tenant admin, you can create, modify, and delete a subtenant from the *ADMINISTRATION* > *Subtenants*. You can also create and manage networks for each subtenant.

For more information on creating networks, see link:sewebiug_define_network_configurations.html[Define network configurations with subnets].

.Steps

. Click *Create Subtenant*.
. Add a name and the code.
The code that represents the subtenant should be unique within a NetApp Service Engine instance and consist of lower-case characters.
. Click *Create*.

NOTE: You can only modify the name of an existing subtenant. Additionally, you cannot delete a subtenant that has storage components associated with it.
