---
sidebar: sidebar
permalink: sewebiug_create_a_host_group.html
keywords:
summary:
---

= Create a host group
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:39.436160
//

[.lead]
There are two ways to create a host group:

* From the Host Groups page, described below.
* As part of creating a new disk. Use this method when you need to create a host group on a block store that has not yet been initialized. For more information see Create a new disk <xref>.
+
It is possible to create an empty host group and map it to a disk as a placeholder. You must update the empty host group to add initiators before you will be able to access the storage.

=== Before you begin

You need the following to create the host group:

* The subtenant, region and zone in which to create the host group.

[NOTE]
If the block store for a subtenant/zone combination has not been previously initialized, you will not be able to create a host group using this method. An alternative is to follow the Create New Disk <xref> process, which allows you to initialize the block store and create a host group as part of the process.   

* A name for the host group
* The host group protocol: iSCSI or FCP
* The list of initiators to add to the group: WWPNs for FC hosts nodes or IQNs for iSCSI host node names. 
* An alias for each initiator; an alias is a simple name to identify the initiator server, or an individual port/interface on the server. For example, Server 4.  

=== Steps

. Display the Host Groups <xref> list.
. Click Create Host Group.
. On the Create Host Group page:
.. Select the protocol: iSCSI or FCP.
.. Select the subtenant, region, and zone and for the host group.
. Specify a name for the host group.
. Select the OS Type: the disk operating system.
. Add the Initiators for the group. For each initiator, specify the alias and the initiator.
. If required, add tags (key-value pairs) to the host group in the Tags section.
. Click Create. This creates the host group. 

=== After you finish

After the host group is created, it is available for mapping to disks.


