---
sidebar: sidebar
permalink: sewebiug_managing_azure_capacity_pools.html
keywords: netapp, keystone, managing, azure, capacity, pools,
summary: Keystone managing Azure capacity pools
---

= Managing Azure capacity pools
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:40.303389
//

[.lead]
This section describes how to manage Azure capacity pools:

[NOTE]
Managing Azure capacity pools requires Customer Admin access.

This section describes how to perform the following tasks:

* View a list of Azure capacity pools
* Add an Azure capacity pool
* Modify Azure capacity pool details
* Delete an Azure capacity pool

=== View a List of Azure capacity pools

The Azure capacity pools list displays a list of capacity pools for a specified subtenant and location. To display the list, select FILE SERVICES > Azure Capacity Pools from the menu.

The list displays simple information about each Azure capacity pool. The action icons next to each Azure capacity pool allow you to modify or delete the Azure capacity pool.

=== Add an Azure capacity pool

This section describes how to add an Azure capacity pool.

==== Before you begin

You will need:

* The subtenant to which the capacity belongs
* The ANF account
* The service level
* A name for the capacity pool
* The size of the pool


==== Steps

. Select FILE SERVICES > Azure Capacity Pools from the menu.
. Click *Create*.
. In the Create Azure Capacity Pool dialog box, specify the Subtenant, the ANF Account, the Service Level, the Name and the size.
. Add tags to the capacity pool if required.
. Click *Create*. When the capacity pool is created the state changes to `Succeeded` (can be viewed in the Azure Capacity Pools list).


=== Modify Azure capacity pool details

Use this method to modify an Azure Capacity Pool’s details. You can modify the service level the size of the pool, and you can add or remove tags.

==== Steps

. Select FILE SERVICES > Azure Capacity Pools from the menu.
. From the list, locate the Azure capacity pool and click the Edit icon.
. In the Manage Azure Capacity Pool dialog box, make any changes as required.
. Click *Update*.

=== Delete an Azure capacity pool

Use this method to delete an Azure capacity pool.

==== Steps

. Select FILE SERVICES > Azure Capacity Pools from the menu.
. From the list, locate the Azure capacity pool and click the Delete icon.
. In the Confirm Delete dialog box, enter the name of the Azure capacity pool to be deleted.
. Click *Confirm*.
