---
sidebar: sidebar
permalink: sewebiug_view_disks.html
keywords: netapp, keystone, view, buckets,
summary: Keystone view disks
---

= View disks
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:39.508947
//

[.lead]
The Disks list displays the disks belonging to the selected tenant. To view the list, select *BLOCK STORAGE > Disks* from the menu.

The disks that are already a part of your existing environment and belong to the storage VMs configured in your NetApp Service Engine, can also be viewed on this screen and be managed as a part of your NetApp Keystone Flex Subscription (Flex Subscription) services. The disks provisioned outside of the NetApp Service Engine are periodically imported and listed on this page with appropriate status codes.

If the imported disks are in acceptable standards of NetApp Service Engine, that is, if all the parameters that are required for making the disks operational are available, they are imported with the status as `Operational` and can be directly managed through NetApp Service Engine. However, some disks might not be in the same standard as the existing disks on NetApp Service Engine. After import, these disks are categorized with `Imported` or `Non-Standard` status. For understanding the disk statuses and the steps to be taken to make them operational, see link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#Object-states[Object states]

In the Disks list, view simple information about a disk such as:

* Disk name
* Path to the disk
* Disk size
* Protocol
* Subtenant to which the disk belongs
* Zone in which disk exists
* Operational state

For more information about how to use the features of a list, see link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view[List view].
