---
sidebar: sidebar
permalink: sewebiug_view_shares.html
keywords: netapp, keystone, view, shares,
summary: Keystone view shares
---

= View file shares
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:39.249287
//

[.lead]
The *Shares* list displays the file shares belonging to the selected Tenant. To display the list, select *FILE SERVICES > Shares* from the menu.

The file shares that are already a part of your existing environment and belong to the storage VMs configured in your NetApp Service Engine, can also be viewed on this screen and be managed as a part of your NetApp Keystone Flex Subscription (Flex Subscription) services. The file shares provisioned outside of the NetApp Service Engine are periodically imported and listed on this page with appropriate status codes.

If the imported file shares are in acceptable standards of NetApp Service Engine, that is all the parameters that are required for making the shares operational are available, they are imported with the status as `Operational` and can be directly managed through NetApp Service Engine. However, some shares might not be in the same standard as the existing shares on NetApp Service Engine. After import, these file shares are categorized with `Non-Standard` status.

[NOTE]
   You can raise a service request for them to be standardized and managed through the NetApp Service Engine portal. For information, see link:https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html[here]

The Shares list displays simple information about each share such as:

* Share name
* Server on which it resides
* Share path
* Subtenant to which it belongs
* Zone in which it exists
* Service level
* Operational state (operational, updating, or contact support)
* Creation dateFor more information about how to use the features of a list, see link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view[List view].
