---
sidebar: sidebar
permalink: sewebiug_managing_subscribed_services_overview.html
keywords:
summary:
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:40.197840
//

[.lead]
When registered with the NetApp Service Engine, you can manage your cloud volumes services (CVS) through the NetApp Service Engine web portal. This includes:

* Azure NetApp Files (ANF)
* (Future) Amazon Web Services (AWS)
* (Future) Google Cloud Platform (GCP) 
+
You can only register existing CVS subscriptions with NetApp Service Engine; to create a new subscription, create the CVS subscription in the normal way and then register it with the NetApp Service Engine using your subscription credentials.
+
This section describes how to manage subscribed services

[NOTE]
Managing subscribed services requires customer administrator access.

You can:

* View a list of subscribed services
* Add a subscribed service 
* Modify subscribed service details
* Delete a subscribed service


