---
sidebar: sidebar
permalink: sewebiug_partner_service_provider.html
keywords: netapp, service, engine, web, portal, partner, service provider
summary: NetApp service engine partner, service provider functions
---

= Roles and operations of service providers and customers
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
//
// 2021-04-21
//
[.lead]
Based on your role of a service provider/partner (used interchangeably) or a customer/tenant (used interchangeably) administrator, the views and functions on the NetApp Service Engine web portal are determined.

== Activities that you can perform as a service provider administrator

As a service provider admin in a multi-tenant environment, you can perform the functions of provisioning, reporting, billing, and managing customers having their own subscriptions, through the NetApp Service Engine web UI. You can perform the following functions:

* View the storage subscribed and provisioned as a part of their Flex Subscription service.
+
[NOTE]
As a service provide, you can sell more capacity to your customers than purchased from NetApp (oversubscription). Tenant subscriptions can extend beyond the current Flex Subscription period, however a warning is displayed at subscription creation time and in dashboards/reports.

* Create, view, modify, and delete zones, regions, tenants, subtenants, and users.
* Manage and host multiple tenants within the Flex Subscription service: Create and manage tenant subscriptions, and view your own Flex Subscription details.
+
[NOTE]
The tenant subscriptions can be created based on the corresponding zones and subscriptions. They are created as per the service levels provided under the subscribed capacity of your Flex Subscription.

* Create file servers and initialize block, file, and object storage as you are aware of the network requirements for provisioning each storage type for your tenants.
* You can also create and manage subnets for your tenants,
* View file shares, disks, and buckets created as a part of your Flex Subscription. Also create and manage object storage groups and users.
* Draw reports for consumption against your NetApp Keystone Flex Subscription, and tenants subscriptions, and usage for all tenants, for using it in the respective billing and rating systems.
* View the billing and reporting for all the tenants and customers and for only the storage subscribed to or provisioned.
* View and manage service requests raised by customers within your own (partner/service provider's) service request tool (integrated with OpsRamp / GSSC).

== Activities that you can perform as a customer/tenant administrator

As a tenant administrator, you can are entitled to view the subscription details of your own tenancy and perform administrative tasks for your subtenants. You can perform the following actions:

* View the storage subscribed and provisioned as a part of your Flex Subscription service.
* Manage and host multiple subtenants and users within the Flex Subscription service.
* View your zones, regions, tenancy, and subnets.
* View file servers and create file shares, disks, and buckets as a part of your Flex Subscription service.
* Draw reports for tenants and subtenant to view the consumption data for only the storage subscribed to or provisioned for your tenancy and subtenants.
* Raise and update service requests within the service provider's service request tool.
+
[NOTE]
For additional subscriptions, you can make use of your service request tool.
