---
sidebar: sidebar
permalink: sewebiug_create_a_disk_from_a_snapshot.html
keywords: netapp, keystone, create, disk, snapshot
summary: Create a disk from a snapshot
---

= Create a disk from a snapshot
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a new disk from an existing snapshot. The new disk, cloned from the snapshot, has the same properties as the disk from which the snapshot is created.

.Steps

. Select *BLOCK STORAGE* from the left navigation pane and select *Disks*. The list of existing disks for your tenancy is displayed.
. Click *Create Disk* and select *Clone from snapshot*. Alternately, if you know the disk whose snapshot you want to use for cloning, you can locate the disk and click the copy button next to it. The disk should be in an operational state.
The *Create Disk from Snapshot* screen is displayed with all the disks for the tenant. You can filter disks by region, zone, and subtenant. You can select any disk that is in operational state. For information about object states, see link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states[Object states]
. Select the checkbox next to the disk that you want and click *Next*. The snapshots for the disk are displayed.

+
[NOTE]
For the selected disk, if you have some snapshots created in your SnapCenter environment outside of NetApp Service Engine, you can find these snapshots imported and listed for your selection. You can select these imported snapshots and clone the new disks from them.

+
You can search for a particular snapshot or select the schedule type to filter the snapshots.
. Select the checkbox next to the snapshot that you want to clone from and click *Next*.
The new disk inherits the properties of the selected snapshot.
. Add *Name* and *Disk Path*. Update the other settings, such as assigning a *Service Level*, and click *Create*.
Select the service level that best matches your needs. As a tenant, you can use only the service levels that are assigned to you by your service provider, and not any other service level, irrespective of whether or not the service provider has subscribed to those service levels.
.After you finish

*Create Disk* is run as an asynchronous job. You can:

* Check the status of the job in the jobs list. For information about tracking jobs, see link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator[here].
* After the job is finished, check the status of the disk in the *Disks* list.
