---
sidebar: sidebar
permalink: sewebiug_create_file_share_from_snapshot.html
keywords: netapp, keystone, create, file share, Snapshot
summary: Create a file share from a Snapshot
---

= Create a file share from a Snapshot
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a new file share from an existing Snapshot. The new file share, cloned from the Snapshot, has the same properties as the file share from which the Snapshot is created.

.Steps

. Select *FILE SERVICES* from the left navigation pane and select *Shares*.
. Click *Create Share* and select *Clone from snapshot*.
The *Select Share* screen is displayed with all the file shares for the tenant. You can filter file shares by region, zone, and subtenant. You can select any file share that is in operational state.
. Select the checkbox next to the file share that you want and click *Next*.
The *Select Snapshot* screen is displayed with all the Snapshots for the file share.

+
[NOTE]
For the selected file share, if you have some Snapshots created in your SnapCenter environment outside of NetApp Service Engine, you can find these Snapshots imported and listed for your selection. You can select these imported Snapshots and clone the new file shares from them.

+
You can search for a particular Snapshot or select the schedule type to filter the Snapshots.
. Select the checkbox next to the Snapshot that you want to clone from and click *Next*.
The new file share inherits the properties of the selected Snapshot.
. Add *Name* and *Share Path*. Update the other settings, such as assigning a *Service Level*, and click *Create*.

.After you finish

* For CIFs type shares only: To make the shares available by host name, your domain administrator should update the DNS records with the CIFS server name and IP address. Otherwise, the share is only accessible through the IP address. For example:
** With DNS records updated, use either the host name or IP to access the share: such as file://hostname/share[\\hostname\share^] or file://IP/share[\\IP\share^]
** With no DNS records updated, you should use the IP address to access the share i.e. file://IP/share[\\IP\share^]
* *Create Share* is run as an link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery—asynchronous[asynchronous job]. You can:
** Check the status of the job in the jobs list.
** After the job is finished, check the status of the share in the *Shares* list.
