---
sidebar: sidebar
permalink: sewebiug_view_disks.html
keywords: netapp, keystone, view, buckets,
summary: Keystone view disks
---

= View disks
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:39.508947
//

[.lead]
The Disks list displays the disks belonging to the selected tenant. To view the list, select *BLOCK STORAGE > Disks* from the menu.

The disks that are already a part of your existing environment and belong to the storage VMs configured in your NetApp Service Engine, can also be viewed on this screen and be managed as a part of your NetApp Keystone Flex Subscription (Flex Subscription) services. The volumes provisioned outside of the NetApp Service Engine are periodically imported and listed on this page with appropriate status codes.

[NOTE]
The imported disks might not be in the same standard as the existing disks on NetApp Service Engine. After import, these disks are categorized with `Non-Standard` status. You can raise a service request from *Support > Service Request > New Service Request* for them to be standardized and managed through the NetApp Service Engine portal.

In the Disks list, view simple information about a disk such as:

* Disk name
* Path to the disk
* Disk size
* Protocol
* Subtenant to which the disk belongs
* Zone in which disk exists
* Operational state (operational, updating, and contact support)

For more information about how to use the features of a list, see link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view[List view].
