---
sidebar: sidebar
permalink: sewebiug_define_network_configurations.html
keywords: netapp, keystone, subnet, subtenant, network, tenant network, IPspace, VLAN, port
summary: Create and delete subnets
---

= Define network configurations for tenants and subtenants
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
A service provider or partner admin can define network configurations for tenants based on their subscription zones and assign VLANs to each network configuration. They can also create a subnet with each VLAN belonging to the same zone and tenancy, and assign it to a subtenant under that tenancy.

A preconfigured tenant network is required creating the subnet. A subnet is required when a subtenant or end customer provisions file servers or block stores. File and block storage VMs are owned by subtenants in NetApp Service Engine, whereas they are owned by IPspaces in ONTAP. When you define the networking boundary at a subtenant level, the subtenant in NetApp Service Engine maps to a single ONTAP IPspace for that zone. This eliminates risk and ensures that two distinct subtenants do not select the same VLAN ID and end up in the same IPspace.

* There can be multiple subnets created in each zone. For each zone under a tenancy, there is an allocated list of VLANs. For all those available VLANs, corresponding subnets can be created. There is a 1:1 mapping between a subnet and a VLAN. Whereas, there is a one is to many mapping between subnets and zone.
* One tenant can have multiple subnets, one for each available VLAN under a zone. They are displayed under a single network configuration for each zone.
* There can be only one VLAN for each network subnet. Each network configuration shows a list of available VLANs.
* Only one subnet can be created for a zone and VLAN combination for a subtenant.

[NOTE]
A tenant admin can only view the network configurations for their tenancy and the subnets for their subtenants.

== Define a network configuration for a tenant

As a partner admin, you can create network configurations for each tenant. A configurable and unique VLAN pool can be allocated to each tenant based on their requirement. When a tenant is deleted, the VLANs associated with it are released back to the tenant VLAN pool.

.Before you begin

* Ensure the tenants have been created
* You should know the zone, VLANs, and port override configuration

.Steps
. From *ADMINISTRATION* > *Tenants*, select the required tenant.
. Click the network  icon. The Networks screen is displayed with the list of network configurations for the tenant.
. Click *Create Network*. Specify the zone, VLAN, and port override, if applicable. If the port override is defined, select the assigned port from the drop-down.
+
[NOTE]
The port override is configured by the support team during zone configuration. If a port override is not specified, the network uses the default port and creates a new VLAN for that tenant.
+

. Click *Create*. The new network configuration is listed for the tenant on the Networks screen.

If the network configuration for a zone is created, you can only assign new VLANs to the network configuration. Click the *+* icon and add the VLAN and port override details. Click *Update*.

== Create a subnet for a subtenant

As a partner admin, you can create subnets for your subtenants from *NETWORKS* > *Subnets*. The subnet definition includes the VLAN ID that is implemented in ONTAP, the CIDR address range, and a route specification. A subnet is aligned to a VLAN within a tenant and zone. You cannot create two subnets with the same VLAN for a zone.

.Before you begin

* The VLAN and zone configuration should already have been complete for the tenant
* You should be aware of the requirements for the subnet to be created

.Steps
. Select the required tenant. The subtenants for whom you create the subnets should be under this tenant.
. Click *NETWORKS* > *Subnets*. You can view the list of subnets created for your subtenants on the *Subnets* page.
. Click *Create Subnet*.
. Specify the subtenant, zone, name of the subnet, VLAN, and Subnet CIDR. You can also add route specification and tags.

+
[NOTE]
In route specification, the *Destination* should be unique and part of the mentioned VLAN, and multiple routes can have the same value for *Metric*.
+

.	Click *Create*.

NOTE: You cannot edit or delete a subnet. You can only edit the tags associated with it.
