---
sidebar: sidebar
permalink: sewebiug_create_object_storage_user.html
keywords: netapp, keystone, create, object, storage, user,
summary: Keystone create object storage user
---

= Create Object Storage User
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

.Before you begin

Because an object storage user belongs to an object storage group, the object storage group must exist before you can create the user.

.Steps

. Navigate to *OBJECT STORAGE > User Management > Users*.
. Make sure the correct subtenant is selected and you have clicked the *Users* tab.
. Click *Create User*.
. In the Create User dialog box:
.. Enter the user name.
.. Select the group to which the member belongs.
. Click *Create*. This creates a job to create the user with the specified settings.

.After you finish

Create user is run as an asynchronous job. You can:

* Check the status of the job in the jobs list. For information, see link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator[Jobs and job status indicator].
* After the job is finished, check the status of the share in the Users list.
