---
sidebar: sidebar
permalink: sewebiug_managing_service_requests_overview.html
keywords: netapp, keystone, managing, service, requests, overview,
summary: Keystone managing service requests overview
---

= Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:40.000190
//

[.lead]
Service requests enable you to raise an issue with the GSSC team so that they can resolve the issue and update the status for you to view.

[NOTE]
You can view the *Support > Service Requests* menu only if you are a partner administrator. As a partner administrator, you can also view list the service requests raised for your selected tenant on the dashboard. You cannot raise a service request with NetApp support if you are a tenant administrator.

The workflow is at link:https://docs.netapp.com/us-en/keystone/sewebiug_service_request_process.html[Service request process]

Place a service request for:

* Backup restoration
* Disaster recovery failover
* A technical issue with NetApp Service Engine
* Non-standard volumes: The volumes that are imported into your Keystone subscription services do share the same standard as the existing disks and file shares on NetApp Service Engine. After import, these disks and file shares are categorized with `Non-Standard` status. You raise a service request for changing their status to a standard one.
* Any other issue that is not covered in this list.

The other topics in this section discuss:

* How to raise a service request
* How to track a service request
* The service request process
