---
sidebar: sidebar
permalink: sewebiug_create_an_object_storage_group.html
keywords: netapp, keystone, create, object, storage, group,
summary: Keystone create an object storage group
---

= Create an object storage group
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Use this method to create an object storage group.

.Steps

. View the list of object storage groups from *OBJECT STORAGE > User Management > Groups*.
. Make sure the correct subtenant is selected and you have clicked the *Groups* tab.
. Click *Create Group*.
. In the Create Group dialog box, enter the group name.
. Select the S3 policy from the list. For information about S3 policies, see https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#specify-permissions-in-a-policy[Specify permissions in a policy].
. Click *Create*. This creates a job to create the group with the specified settings.

.After you finish

Create object storage group is run as an asynchronous job. You can check the status of the job in the jobs list. For information about tracking jobs, see link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator[here].
