---
sidebar: sidebar
permalink: sewebiug_create_a_disk_from_a_snapshot.html
keywords: netapp, keystone, create, disk, Snapshot
summary: Create a disk from a Snapshot
---

= Create a disk from a Snapshot
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a new disk from an existing Snapshot. The new disk, cloned from the Snapshot, has the same properties as the disk that the Snapshot belongs to.

.Steps

. Select *BLOCK STORAGE* from the left navigation pane and select *Disks*.
. Click *Create Disk* and select *Clone from snapshot*.
You can filter disks by region, zone, and subtenant.
. Select the checkbox next to the disk that you want and click *Next*.
All the Snapshots associated with the disk are listed. You can search for a particular Snapshot or select the schedule type to filter the Snapshots.
. Select the checkbox next to the Snapshot that you want to clone from and click *Next*.
The new disk inherits the properties of the selected Snapshot.
. Add *Name* and *Disk Path*. Update the other settings as required and click *Create*.

.After you finish

*Create Disk* is run as an link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html#disaster-recovery—asynchronous[asynchronous job]. You can:

* Check the status of the job in the jobs list.
* After the job is finished, check the status of the disk in the *Disks* list.
