---
sidebar: sidebar
permalink: sewebiug_billing.html
keywords: netapp, keystone, monthly charges, billing, flex subscription, flex utility, cloud services
summary: View and download billing details
---

= View billing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can view the monthly charges for all the subscribed services on your Keystone Flex Subscription (Flex Subscription).

You can view the billing details for the previous months and also the projected billing for the current month, based on the usage trends of the historical data. The billing against the capacity in burst for each month is highlighted. Projected billing covers the capacity that is in burst at present and the expected increase in burst capacity for the billing period.

You can sort the data in the table by month and view the list of all the storage subscriptions for any given month.

.Steps

. Select *ADMINISTRATION* > *Billing* from the menu.
+
[NOTE]
You can also click the arrow on the top right corner of the *Monthly Charges* widget on the dashboard or any bar that represents a month in the widget to view the Billing page. All your subscriptions for the selected month are displayed.
+

. Optionally, hover over the bar representing a month to view additional details.
. Select any month listed in the table.
All your subscriptions for the month, along with the associated billing, is displayed in the table. The charges are split up as per the committed capacity and burst usage.
