---
sidebar: sidebar
permalink: sewebiug_modify_a_disk.html
keywords:
summary:
---

= Modify a disk
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-10-20 10:59:39.608174
//

[.lead]
You can change the disk name, the host group mapping, performance service level, capacity, and snapshot policy.

Using this method,  you can move your disks to different performance levels if available.

=== Before you begin

The disk must be in an operational state.

=== Steps

. Display the Disks list <xref>.
. Locate the disk in the list and click the Edit icon for that disk. (For details about working with items in lists,  see List view actions <xref>).
. Make any changes as required; refer to Create new Disk <xref> for field descriptions.
. Click Done. This creates a job to modify the disk.

=== After you finish

Modify disk is run as an asynchronous job <xref>. You can:

* Check the status of the job in the jobs list.
* After the job is finished, check the status of the disk in the Disks list.


