---
sidebar: sidebar
permalink: sewebiug_modify_a_file_share.html
keywords: netapp, keystone, modify, file, share,
summary: Keystone modify a file share
---

= Modify a file share
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can change the share name, service level, capacity, snapshot policy, export policy,  Access Control List (ACL), and tags in a file share.

[NOTE]
Using this method,  you can move your shares to different service levels if available. You can change the share type only if the server supports the respective services.

.Before you begin

The file share must be in the operational state. For understanding volume statuses and the steps to be taken to make them operational, see link:sewebiug_view_disks.html[View disks] and link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states[Object states]

.Steps

. View the link:sewebiug_view_shares.html#view-shares[Shares list].
. Locate the share in the list and click the Edit icon for that share. (For details about working with items in lists,  see link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view[List view actions]).
. Make any changes as required;  for field descriptions, see link:sewebiug_create_a_new_file_share.html[Create a new file share].
. Click *Done*. This creates a job to modify the share.

.After you finish

Modify share is run as an asynchronous job. You can:

* Check the status of the job in the jobs list. For information about tracking jobs, see link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator[here].
* After the job is finished, check the status of the share in the Shares list.
