---
sidebar: sidebar
permalink: sewebiug_delete_an_s3_key_for_a_user.html
keywords: netapp, keystone, s3, key, user,
summary: Keystone delete an S3 key for a user
---

= Delete an S3 key for a user
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Use this method to delete an S3 key for a user.

.Steps

. View the object storage user link:sewebiug_view_the_object_storage_group_and_users.html[View object storage group and users].
. Make sure the correct subtenant is selected and you have clicked the *Users* tab.
. Locate the user in the list and click the Key icon for that group.
+
For details about working with items in lists, see link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions[List view actions].

. The *Manage S3 Keys* dialog displays showing the list of keys for the user.
. In the list of keys, locate the key to delete and click the *Delete* icon.
. Click *Confirm* to confirm the delete action. The key is removed from the list of user keys.
. Click *Close* to close the Manage S3 Keys dialog box.
