---
sidebar: sidebar
permalink: sewebiug_create_a_disk_from_a_snapshot.html
keywords: netapp, keystone, create, disk, Snapshot
summary: Create a disk from a Snapshot
---

= Create a disk from a Snapshot
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a new disk from an existing Snapshot. The new disk, cloned from the Snapshot, has the same properties as the disk from which the Snapshot is created.

.Steps

. Select *BLOCK STORAGE* from the left navigation pane and select *Disks*.
. Click *Create Disk* and select *Clone from snapshot*.
The *Select Disk* screen is displayed with all the disks for the tenant. You can filter disks by region, zone, and subtenant. You can select any disk that is in operational state.
. Select the checkbox next to the disk that you want and click *Next*.
The *Select Snapshot* screen is displayed with all the Snapshots for the disk.

+
[NOTE]
For the selected disk, if you have some Snapshots created in your SnapCenter environment outside of NetApp Service Engine, you can find these Snapshots imported and listed for your selection. You can select these imported Snapshots and clone the new disks from them.

+
You can search for a particular Snapshot or select the schedule type to filter the Snapshots.
. Select the checkbox next to the Snapshot that you want to clone from and click *Next*.
The new disk inherits the properties of the selected Snapshot.
. Add *Name* and *Disk Path*. Update the other settings, such as assigning a *Service Level*, and click *Create*.

.After you finish

*Create Disk* is run as an asynchronous job. You can:

* Check the status of the job in the jobs list. For information about tracking jobs, see link:https://docs.netapp.com/us-en/keystone/sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator[here].
* After the job is finished, check the status of the disk in the *Disks* list.
