---
sidebar: sidebar
permalink: sewebiug_billing.html
keywords: netapp, keystone, monthly charges, billing, flex subscription, flex utility, cloud services
summary: View and download billing details
---

= View billing
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can view the monthly charges for all the subscribed services on your NetApp Keystone Flex Subscription (Flex Subscription) on the NetApp Service Engine dashboard and Billing screen.

You can view the billing details for all your subscribed services for Flex Subscription for the previous months. The billing against the capacity in burst for each month is highlighted.

NOTE: If any of your subscriptions are billed annually, the invoice reflects the prorated amount instead of actual monthly invoice amount.

You can sort the data in the table by month and view the list of all the storage subscriptions for any given month.

.Steps

. Select *ADMINISTRATION* > *Billing* from the menu.
+
[NOTE]
You can also click the arrow on the top right corner of the *Monthly Charges* widget on the dashboard or any bar that represents a month in the widget to view the Billing page. All your subscriptions for the selected month are displayed.
+

. Optionally, hover over the bar representing a month to view additional details.
. Select any month listed in the table.
All your subscriptions for the month, along with the associated billing, is displayed in the table. The charges are split up as per the committed capacity and burst usage.
