---
sidebar: sidebar
permalink: sewebiug_managing_subscriptions.html
keywords: netapp, keystone, managing, subscriptions,
summary: Keystone managing subscriptions
---

= Managing subscriptions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Managing subscriptions includes assigning service levels to your NetApp Keystone Flex Subscription (Flex Subscription) and tenant subscription services or allocating and changing capacities to the service levels by using the NetApp Service Engine interface.

The Flex Subscriptions represented by the relationship between the service providers/partners and NetApp and the tenant subscriptions represent the relationship between the service provider and their tenants and subtenants (end customers). When NetApp admins or GSSC creates Flex Subscription services for partners and tenants, it implies that the storage allocation has been accomplished. However, unless the service levels are created and the corresponding capacity allocation is complete, storage cannot be consumed by subtenants or end customers. Partner admins can manage storage for their Flex Subscription and tenant subscriptions. Tenant admins can only view the tenant subscription details and services for their own tenancy.

== Manage Flex Subscription (Keystone Subscriptions)

If you are a partner admin, you can view and manage your Flex Subscription services from *SUBSCRIPTIONS* > *Keystone Subscriptions*. *Keystone subscriptions* represent the Flex Subscription services created by NetApp admins for partners. Partner admins can view their Flex Subscription services and create service requests to:

* Increase the capacity of a subscription
* Add a service to a subscription (assign service level and capacity)

Service requests are received and addressed by the support team.

You can also view and manage the data protection and advanced protection services that you are subscribed to, in separate tabs. For information, see link:index.html#flex-subscription[Data Protection and Data Protection Advanced]. 

=== Increase the capacity of a subscription

You can increase the committed capacity for any of the subscribed service levels to meet growth requirements.

.Steps

. Select the subscription that you to want to increase capacity for from the drop-down menu.
. Click *Increase Capacity* for the service level that you want.
. Specify the capacity (in TiB) required.
. Click *Confirm*.You come back to the Manage Keystone Subscriptions page.
. Click *Submit Changes*. A service request is created for GSSC increase the capacity. You can view and track the progress of the service request by the SR number displayed in a message.
For information on tracking, see link:sewebiug_track_a_service_request.html[Track a service request].

=== Add a service to a subscription

You can add a service to a subscription. Adding a service includes assigning a service level to your subscription and specifying the capacity for the same service level.

Each subscription can have one of each service levels. For example, if your subscription already contains an Extreme and a Standard service, you can add a Premium or Block service.

.Steps

. Select the service level that you to want to add to your subscription from the drop-down menu.
. Click *Add service*.
. Select the service level that you want to subscribe to from the drop-down menu, for example `Extreme-tiering`, and add the capacity (in TiB) that you want to commit to the service level.
. Click *Confirm*. You come back to the Manage Keystone Subscriptions page.
. Click *Submit Changes*. A service request is created for GSSC assign the service level to your subscription. You can view and track the progress of the service request by the SR number displayed in a message.

For information on tracking, see link:sewebiug_track_a_service_request.html[Track a service request].

== Manage tenant subscriptions

If you are a partner admin, you can create, view, and update your tenant subscriptions from *SUBSCRIPTIONS* > *Tenant Subscriptions*. If you are a tenant admin, you can only view the subscriptions.

=== Create and edit a tenant subscription

You can create new subscriptions for your tenants.

.Steps

. Click *New Subscription*.
. Specify the region, zone, subscription term, rate plans, and other details.
The tenant subscription is assigned to a Keystone Subscription based on the zone selected. This is because each Keystone Subscription is tied to a zone.

+
[NOTE]
You cannot create overlapping subscriptions. The start date should be at least the next day as subscriptions start a day ahead of the specified start date. Additionally, it cannot be more than 30 days from the current date.

+
. Click *Create*.

You cannot delete any subscriptions. You can only edit existing tenant subscriptions and add new service levels, increase the committed capacity for a service level, and add tags to subscriptions.

If you are a partner administrator, you can edit tenant subscriptions. You can add new service levels to a subscription and edit the capacities of the already added service levels. To add a new service level, follow these steps:

.Steps

. Select the subscription that you want to edit by clicking the `+` icon.
. On the *Add a new service level to subscription* page, select the new service level and add the required capacity. If the service level is already added, you cannot add or delete it.
. Click *Update*.

You can also add tags by clicking the tags icon for the subscription.

To edit the subscribed capacities to the service levels that are already assigned to the subscription, follow these steps:

.Steps

. Click and expand the subscription that you want to edit by clicking the `v` icon. The service levels in that subscription are displayed.
. Select the service level that you want to edit by clicking the respective edit pen icon.
. Change the rate plan by increasing or decreasing the capacity in TiBs.
. Click *Update*.
