---
sidebar: sidebar
permalink: sewebiug_create_file_share_from_snapshot.html
keywords: netapp, keystone, create, file share, snapshot
summary: Create a file share from a snapshot
---

= Create a file share from a snapshot
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can create a new file share from an existing snapshot. The new file share, cloned from the snapshot, has the same properties as the file share from which the snapshot is created.

.Steps

. Select *FILE SERVICES* from the left navigation pane and select *Shares*.
. Click *Create Share* and select *Clone from snapshot*. Alternately, if you know the share whose snapshot you want to use for cloning, you can locate the file share and click the copy button next to it. The share should be in an operational state. For information about object states, see link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states[Object states].
The *Create Share from Snapshot* screen is displayed with all the file shares for the tenant. You can filter file shares by region, zone, and subtenant. You can select any file share that is in operational state.
. Select the checkbox next to the file share that you want and click *Next*. The snapshots for the file share are displayed.
+
[NOTE]
For the selected file share, if you have some snapshots created in your SnapCenter environment outside of NetApp Service Engine, you can find these snapshots imported and listed for your selection. You can select these imported snapshots and clone the new file shares from them.

+
You can search for a particular snapshot or select the schedule type to filter the snapshots.
. Select the checkbox next to the snapshot that you want to clone from and click *Next*.
The new file share inherits the properties of the selected snapshot.
. Add *Name* and *Share Path*. Update the other settings, such as assigning a *Service Level*, and click *Create*.

.After you finish

* For CIFs type shares only: To make the shares available by host name, your domain administrator should update the DNS records with the CIFS server name and IP address. Otherwise, the share is only accessible through the IP address. For example:
** With DNS records updated, use either the host name or IP to access the share: such as file://hostname/share[\\hostname\share^] or file://IP/share[\\IP\share^]
** With no DNS records updated, you should use the IP address to access the share i.e. file://IP/share[\\IP\share^]
* *Create Share* is run as an asynchronous job. You can:
** Check the status of the job in the jobs list. For information about tracking jobs, see link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator[here].
** After the job is finished, check the status of the share in the *Shares* list.
