---
sidebar: sidebar
permalink: sewebiug_add_a_user.html
keywords: netapp, keystone, add, user,
summary: Keystone add a user
---

= Add a user
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
This section describes how to add a user.

=== Before you begin

You need:

* The tenants to which the user should be given access.
* The role that the user is to be granted within each tenancy. A user can have only one role within a tenancy.

=== Steps

. Select *ADMINISTRATION > Users* from the menu.
. Click *Create User*.
. In the Create User dialog box, specify the user name, email address, first name, last name, display name, and password for the user.
. Select the primary tenant and the role of the user in that tenancy.
+
[NOTE]
You can assign privileges to a user based on their role, such as a NetApp administrator, NetApp administrator with read only privileges, partner administrator, or tenant administrator. Based on your role, you can view the roles of different users within your environment and assign roles to newly created or existing users.
+

. To add additional tenancies, click *Add Tenancy* to display new entry fields and select the tenant and the role of the user in that tenancy.
. Click *Create*.
