---
sidebar: sidebar
permalink: sewebiug_managing_subscriptions.html
keywords: netapp, keystone, managing, subscriptions,
summary: Keystone managing subscriptions
---

= Managing subscriptions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can view and manage your Keystone subscriptions and Tenant Subscriptions using the NetApp Service Engine interface.

For information on accounts, subscriptions, and services, see link:sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html[Billing Accounts, Subscriptions, Services, and Performance].

== Keystone Subscriptions

If you are a partner admin, you can view and manage your Keystone Subscriptions from the *Keystone Subscriptions* menu available as part of *SUBSCRIPTIONS*.Keystone subscriptions are created by NetApp admins and can only be viewed and updated by partner admins.

You can also view and manage the data protection and advanced protection services that you are subscribed to.

=== Increase the capacity of a subscription

You can increase the committed capacity for any of the subscribed service levels to meet growth requirements.

.Steps

. Select the subscription that you to want to increase capacity for from the drop-down menu.
. Click *Increase Capacity* for the service level that you want.
. Specify the capacity (in TiB) required.
. Click *Confirm*.

=== Add a service to a subscription

You can add a service to a subscription. A subscription might only have one of each performance level, for example, if your subscription already contains an Extreme and a Standard service, you can add a Premium or Block service.

.Steps

. Select the subscription that you to want to increase capacity for from the drop-down menu.
. Click *Add service*.
. Select the subscription service that you want to add from the drop-down menu and add the capacity (in TiB) that you want to commit to the service level.
. Click *Confirm*.

== Tenant Subscriptions

If you are a partner admin, you can create, view, and update your Tenant Subscriptions from the *Tenant Subscriptions* menu available as part of *SUBSCRIPTIONS*. If you are a tenant admin, you can only view the subscriptions.

=== Create a tenant subscription

You can create new subscriptions for your tenants.

.Steps

. Click *New Subscription*.
. Specify the region, zone, subscription term, rate plans, and other details.
The tenant subscription is assigned to a Keystone Subscription based on the zone selected. This is because each Keystone Subscription is tied to a zone.

+
[NOTE]
You cannot create overlapping subscriptions. The start date should be at least the next day as subscriptions start a day ahead of the specified start date. Additionally, it cannot be more than 30 days from the current date.

+
. Click *Create*.

NOTE: You cannot delete any subscriptions. You can only edit existing tenant subscriptions and add new service levels, increase the committed capacity for a service level, and add tags to subscriptions.
